### ISSUE TITLE
Annotation colors are different from those on the Zotero client

### ISSUE THREAD

**Issue by mrtcode** [zotero/zotero-ios#1002]
https://forums.zotero.org/discussion/comment/472702/#Comment_472702

**Comment by mrtcode** [comment]
I mean I can reproduce the issue, and the color code that comes from the iOS app is slightly different than it should be.

**Comment by mvasilak** [comment]
@mrtcode can you please provide steps to reproduce? I tried with latest versions of macOS and iPadOS, and I get the same color hex values.

**Comment by mrtcode** [comment]
1) Open any PDF file on iOS app.
2) Select highlighting tool with the red color and highlight a text.
3) Open the some file in Zotero client.
4) Select highlighting tool with the red color and highlight another text.

Result: iOS app created annotation has `#ff4747` (incorrect), while the client created annotation has `#ff6666` (correct).

Version 1.0.41 Build 282.

**Comment by mvasilak** [comment]
Hmm, tried these steps with iOS version `1.0.41 Build 282` and macOS version `7.0.3-beta.3+6f9abaaff` and I only see `#ff6666` as the color. Confirmed it also by checkng the annotation data via the API, between every step. @mrtcode can you mention the iOS version you have, it might be relevant. Did you use a pencil?
