### ISSUE TITLE
Item detail attachment bug

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#1034]
When you open a standalone attachment (or probably any attachment) item detail, there is a bug which disables opening the PDF. Repro steps:
- open item detail
- open attachment via top "View PDF" button
- close PDF reader
- enable editing
- disable editing
- the attachment is now grayed out and can't be tapped

**Comment by mvasilak** [comment]
@michalrentka did you see this on production on or dev master? I couldn't reproduce it on either.

**Comment by michalrentka** [comment]
> @michalrentka did you see this on production on or dev master? I couldn't reproduce it on either.

I edited the description, I thought I tapped the attachment but I can reproduce on current master when I tap the "View PDF" button, I'll take a look at it now
