### ISSUE TITLE
"Remove Downloaded File" option in long-press menu for attachments

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#219]
If a file has been downloaded, it should be possible to remove it from the long-press menu in the item details pane

**Comment by michalrentka** [comment]
@dstillman this is already implemented. The context menu option shows up when the attachment has been downloaded. Does it not work for you?

**Comment by dstillman** [comment]
I think this was missing or buggy when I created this, but yes, we're good now.
