### ISSUE TITLE
Clarify Local Storage pane

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#224]
https://forums.zotero.org/discussion/88325/ios-app-delete-attachments-feature-in-local-storage-is-unclear

At least the confirmation prompt should be clearer

**Comment by michalrentka** [comment]
Any idea how to clarify this except changing the confirmation prompt? Should we add additional explanation there? Rename "Temporary Files"?

**Comment by dstillman** [comment]
Remind me what Temporary Files is for?

**Comment by michalrentka** [comment]
@dstillman currently when you share a PDF it's generated with annotations and gets stored in this cache folder. It should be deleted when you're done, but bugs can happen and I wanted to have a way to actually clear this stuff. If it's too confusing we can just remove it and clear it when user clears all data.

**Comment by dstillman** [comment]
Yeah, I don't think people should have to worry about this.

First, if we were going to display it at all, we could do so only when there were actually files. No need for people to see it otherwise.

But I'm not sure there's much value to showing it except in some dev mode, unless there's additional information we could display to users that might allow us to actually debug it. (And even then, the odds of actionable information making it back seem slim.)

Either way, we should probably just clear 1) on any manual delete operation (which would suggest that people were trying to clear space), 2) periodically, and 3) if we get a low-storage alert from the system (assuming that's a thing).

**Comment by michalrentka** [comment]
@dstillman what about the rest? Keep it as it is?

**Comment by dstillman** [comment]
I already fixed the rest.
