### ISSUE TITLE
Consider using different icons for collections that contain subcollections

### ISSUE THREAD

**Issue by tnajdek** [zotero/zotero-ios#231]
I believe it makes the UI easier/quicker to read, we do this on touch in web library:

<img width="283" alt="Screenshot 2021-03-15 at 23 22 05" src="https://user-images.githubusercontent.com/214628/111228888-44033d00-85e5-11eb-88b4-b98c1d76cf77.png">

**Comment by michalrentka** [comment]
@flachware did we have such icon?

**Comment by flachware** [comment]
I guess not, here you go:
[folders.zip](https://github.com/zotero/zotero-ios/files/6248772/folders.zip)
