### ISSUE TITLE
Share extension doesn't always appear

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#235]
I've seen this a few times, and @stakats just had it not appear and then reappear after trying again. The other day, I had to either restart my device or reinstall the app to get it to appear (I can't remember which I did). There might have been a report in the forums that was saying this happened.

Maybe this is just iOS bugginess, but if there's anything we have control over here, we should take a look at it.

**Comment by michalrentka** [comment]
@stakats @dstillman any updates on this? Has the last change actually fixed it?

**Comment by dstillman** [comment]
I haven't seen it again, though I don't know if that's meaningful — it was working for me immediately before the update that was meant to fix it.

**Comment by dstillman** [comment]
Closing this for now. If someone sees it again, we can reopen.
