### ISSUE TITLE
Expand All/Collapse All options for collections

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#249]
Not sure where we want to put this.

**Comment by michalrentka** [comment]
I've got no idea where to put this. Do I add another row below navigation bar?

**Comment by michalrentka** [comment]
@dstillman I can replace the "+" icon with "..." menu icon and when you tap "..." it would show options "add collection", "collapse/expand all". Does that sound ok?

**Comment by michalrentka** [comment]
@dstillman can you send me a screenshot of the bug? The line height doesn't seem to change for me.

**Comment by dstillman** [comment]
Sent. I guess it's not actually the line height changing, since the same things end up in the same place. There are just some weird animations on things that shouldn't actually be changing.

**Comment by dstillman** [comment]
Is there any way to create a context menu on the library title (e.g., "My Library") instead of All Items? I almost suggested All Items, but it's sort of illogical there, even if having a context menu itself there is more natural. (One might even think that it meant that it would expand all items, as you can do in the client, rather than collections.)

**Comment by michalrentka** [comment]
@dstillman is the context menu better now?

**Comment by dstillman** [comment]
Weird! But good for now.

And animation for non-changing collections is fixed.
