### ISSUE TITLE
Move collection expand/collapse to the left of item count

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#251]
Not sure if this will work but let's try it

**Comment by dstillman** [comment]
Maybe we should even try it to the left of the collection icon, like on desktop, with the collection icon indented for all rows. It doesn't work in its current position — along with messing up the item counts, it just really looks like a navigational arrow, and I'm not sure how much that would change even with a different icon. It's particularly confusing in the share extension, with no item counts, where it really seems like the whole row is just for navigation.

**Comment by michalrentka** [comment]
@dstillman I'd say it works better on left side, on right side when badges are optional it looks weird when it's in different positions. I also made the icon a bit smaller so that it doesn't look like the navigation arrow (#252).

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-03-24 at 14 10 31](https://user-images.githubusercontent.com/1022956/112316006-fbb1e200-8caa-11eb-8528-c8325ff2d36f.png)

**Comment by michalrentka** [comment]
@dstillman does this seem ok? To me this looks usable.

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-03-24 at 21 16 40](https://user-images.githubusercontent.com/1022956/112377919-94198800-8ce6-11eb-89c9-faead0f67abf.png)

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-03-24 at 21 16 15](https://user-images.githubusercontent.com/1022956/112377948-9c71c300-8ce6-11eb-818a-69d077b2c6d3.png)

**Comment by dstillman** [comment]
It's a little tight, visually. I think we need to give a little more space between the arrow and collection icon — somewhere in between the two versions. (If there's an easy way for me to play with this in Xcode, I can.)

**Comment by michalrentka** [comment]
The easiest would be to try manipulating the SwiftUI version in share extension. Check ZShare -> Views -> AllCollectionPickerView.swift. `CollapsibleCollectionRow` and `CollapsibleLibraryRow` have `.offset(x: -(geometry.size.height * 0.75))` which says how much the chevron button overlaps with the icon. And `ListView` on top has `baseCellOffset` set to 28, which states the minimal offset from the left side. You can play with those two to create more space on level 0 and move the chevron around.

**Comment by dstillman** [comment]
Yeah, so, visually, I think something like 0.92 would work. But at least in the simulator the tap target for the collection icon seems to extend significantly into the whitespace between the two. Haven't tried on-device, but if there's any way to keep most of that whitespace as part of the chevron target, that would probably help.

**Comment by michalrentka** [comment]
Ok, I adjusted it and fixed the tappable area in SwiftUI views.

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-03-25 at 09 01 00](https://user-images.githubusercontent.com/1022956/112439251-2f434980-8d49-11eb-92be-92d772011668.png)
![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-03-25 at 09 04 46](https://user-images.githubusercontent.com/1022956/112439276-366a5780-8d49-11eb-84f8-363a35ff1f6e.png)
