### ISSUE TITLE
Subsequent highlights merged and text omitted

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#253]
https://forums.zotero.org/discussion/88508/ios-app-not-showing-all-annotations

Getting more info, but seems like a bug of some sort

**Comment by dstillman** [comment]
Do we have any idea what's going on with this?

Something about the pencil?

**Comment by michalrentka** [comment]
@dstillman so I just found out that when you highlight something and then create another highlight with same color which overlaps the first highlight, PSPDFKit reports this as a change to the original highlight. Which kind of makes sense. When you create overlapping highlights with the same color, you can't recognize which is which normally.

That doesn't explain her first report where there are gaps in highlights. That may either be a different issue or PSPDFKit thought they are close enough to merge them. 

Not sure how to deal with this though. It doesn't seem to be possible to disable this. We could recommend to change colors when highlighting many sentenced which are near each other, which can be annoying. Controls on Apple pencil 2 might help with that, but still...

**Comment by dstillman** [comment]
We definitely can't recommend different colors. People use colors for organizational purposes.

Automatically joined annotations would explain the larger bounding box, but it wouldn't explain the missing extracted text, right?

**Comment by michalrentka** [comment]
> Automatically joined annotations would explain the larger bounding box, but it wouldn't explain the missing extracted text, right?

That's actually my fault and can be fixed. I didn't expect changes to annotations other than rect change (moving them) in the PDF document. But that doesn't fix the actual issue.

**Comment by dstillman** [comment]
But we don't otherwise support modifying highlights, do we? So couldn't we see that the highlight was modified with new rects and instead create a separate annotation with the new rects?

**Comment by michalrentka** [comment]
@dstillman I could do that, but it feels hacky and kills all PSPDFKit optimisations in place. PSPDFKit updates the annotation internally and lets me know, then I have to remove that annotation and create 2 new ones. The document has to re-render certain parts multiple times. It will probably also create weird animation and flashing of disappearing/appearing highlights. It may not be too visible to the user and we can test it though. I just wanted to avoid that.

**Comment by michalrentka** [comment]
So actually I can't even do that. When PSPDFKit reports a change, I get the new rects array with merged annotations and from memory I know original rects of first annotation. But if the new annotation overlaps the old one I don't know where it started. I could create new annotation where the old one ends, but that might create additional confusion.

**Comment by michalrentka** [comment]
PSPDFKit support pointed me to their configuration API where I can disable this merging completely! So all should be good from now.
