### ISSUE TITLE
Collection sort order should match client

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#259]
https://forums.zotero.org/discussion/88617/ios-beta-collection-sort-order-doesnt-match-desktop-and-web

In the client I think we just get this from [Intl.Collator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator) based on the current locale.

I didn't experiment to see what we're doing now, other than that punctuation isn't sorting first. If there's a locale-based sort that we're not currently using, we should try that, since it might use the same Unicode algorithm.

**Comment by dstillman** [comment]
Another report that suggests we're not using a proper Unicode collation:

> Letters with accents such as É puts the collection at the end of the list, it should be next to the letter E

**Comment by michalrentka** [comment]
@dstillman I implemented this, but I'm seeing difference between iOS and desktop order.

iOS:          "A B C Č D E É"
Desktop:  "A B Č C D É E"

In my language the iOS order makes sense while desktop doesn't. But both are set to english and I'm not sure what order would make more sense in english.

I'm using iOS built-in localised sort based on system locale, so I can't change this anyway. But if this seems wrong I can try looking for third-party solutions.
