### ISSUE TITLE
Share extension: Show Recents in main view

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#266]
If possible, we should show Recents as a flat radio list in the main window, so you can just tap on a recent collection and tap Save without having to navigate to the separate collections view.

**Comment by michalrentka** [comment]
@dstillman does this look ok? You can pick between the currently selected and 4 other most recently used collections. Or you can tap "Choose Other" (probably needs to be renamed) and you are taken to collection picker.

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-04-09 at 16 06 48](https://user-images.githubusercontent.com/1022956/114192295-9cf89380-994d-11eb-8d93-8ccd2041258f.png)

**Comment by dstillman** [comment]
"Choose Other" → "More"
