### ISSUE TITLE
Note changes not being saved

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#268]
https://forums.zotero.org/discussion/88838/ios-modifications-on-existing-notes-are-not-saved

I can't reproduce this, but something's definitely wrong here.

> [ERROR] Zotero(+0004202): ItemDetailStore: can't store note - objectNotFound. [(374) ItemDetailActionHandler.saveNote(key:text:in:); com.apple.main-thread; 1617573192.759305]

**Comment by michalrentka** [comment]
Fixed. This only happened when you created a new note, saved the item with the new note and then tried to edit the note again without leaving the screen, so that's why you couldn't reproduce.
