### ISSUE TITLE
"Show Items from Subcollections" should be the setting title

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#269]
No need for the "Subcollections" title

![Screen Shot 2021-04-08 at 5 31 22 AM](https://user-images.githubusercontent.com/783082/114003372-af7aac00-982b-11eb-8aff-e1c6242b942e.png)

**Comment by michalrentka** [comment]
@dstillman it looked weird with long big bold title

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-04-08 at 11 34 17](https://user-images.githubusercontent.com/1022956/114003825-6001a380-985e-11eb-9370-e77fcae8e655.png)

**Comment by dstillman** [comment]
It doesn't have to be bold, but that's all it should say.

**Comment by dstillman** [comment]
For now I think we should just make it not bold — like most settings on iOS — and when we add other settings to General we can see whether we want the title/subtitle for those and see what makes the most sense.
