### ISSUE TITLE
Share extension: Some weirdness in MRU collection list

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#273]
1) If you select a collection that's already on the list, it duplicates it instead of just moving the existing one to the top.

2) I'm having trouble reproducing it, but at one point I think I selected a collection from the list and then the list got shorter the next time.

**Comment by michalrentka** [comment]
@dstillman 
1. Should be fixed
2. Not sure if you mean this, but this can happen: 
        - let's say you only saved to 1 collection with name "A" and you have "My Library" selected in main app
        - the share extension would show "My Library", "A", "More"
        - you choose "A" and save
        - you open the extension again and you see "A", "More", because A is now selected and also recent, so the list got shorter

So this happens because we combine currently selected and recent collections and I'm not sure how to do this differently. If you have max number of recent collections this is not noticeable.

**Comment by michalrentka** [comment]
I updated it so that this is reflected immediately, not sure whether that's better or worse.

**Comment by dstillman** [comment]
OK, (2) makes sense, and actually happens in the connector as well.
