### ISSUE TITLE
Improved items list tap handling

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#278]
Current behavior:

- If an item has a child PDF attachment, we show the PDF icon
- Tapping on a row with a PDF downloads and opens the PDF
- Tapping an item with a DOI opens the DOI in the system browser
- Tapping on any other item opens the item pane, including items with URLs and items with snapshots

Desired behavior:

- All rows with actions have an icon
  - PDF
  - Snapshot
  - Some sort of URL/link icon for DOI/URL
- If no action, there's no icon, and a tap opens the item pane as it does now
- Snapshots open in a full-screen webview
- DOIs/URLs both open in a full-screen webview

Things to do later in separate issues:

- Ideally we would show images and text files in-app, and would show an image/document icon in the items list as appropriate. As long as they can only trigger the share dialog, they should be ignored as items list actions in favor of any URL/DOI and shouldn't have an icon.
- Ideally we'll eventually have HTML annotation, but before then we could think about [providing a way to take child notes](https://forums.zotero.org/discussion/89151/ios-feature-request-snapshots-should-be-accessible-in-the-same-way-as-pdfs), similar to how you can in the desktop PDF reader, if we think we can make it work in terms of screen real estate. We'd want ability to open/close note pane, similar to annotation sidebar.
- If we got child notes working for snapshots, we could consider using the same thing for live URLs, since it's presumably just going to be the same webview (at least until we have HTML annotations).
- Ideally the DOI/URL webview would work such that, if you didn't have a PDF in your library but had access to it online, you could browse to the PDF right in the webview. And ideally you could even tap a toolbar button to save the PDF as a child attachment.

**Comment by michalrentka** [comment]
@dstillman do we use existing icons?

PDF:
![attachment-list-pdf@3x](https://user-images.githubusercontent.com/1022956/115530555-2b490f80-a294-11eb-8da9-8bce94b92219.png)

Snapshot (this needs an update for downloaded snapshot):
![attachment-detail-webpage-snapshot@3x](https://user-images.githubusercontent.com/1022956/115530635-3d2ab280-a294-11eb-8209-de8025198655.png)

URL/DOI (needs to be scaled down):
![attachment-detail-linked-url@3x](https://user-images.githubusercontent.com/1022956/115530706-4e73bf00-a294-11eb-86e8-d0e3c58dbc57.png)

**Comment by dstillman** [comment]
The URL/DOI one might be a little much but let's try it.

**Comment by michalrentka** [comment]
@flachware if you have some spare time could you create a "downloaded snapshot" icon? I'm not sure how it'd work out, but for now just the blue line would probably be enough.

**Comment by flachware** [comment]
For the URL/DOI icon we can probably just use the `web-page-linked` item type icon, I can provide the 1–3x versions in the size we have.

But the snapshot icon needs to have all four states (download, missing, failed, downloaded) like the PDF and Document icon, right?

**Comment by michalrentka** [comment]
> But the snapshot icon needs to have all four states (download, missing, failed, downloaded) like the PDF and Document icon, right?

Ideally yes

**Comment by dstillman** [comment]
The concern with `web-page-linked` would just be that it's a little hard to quickly distinguish from actual file attachments, so that you understand that you're about to open a remote webpage — and, perhaps more importantly, so that you can tell easily when you're opening a snapshot rather than the live page. And this icon will likely appear for almost everything without an actual file attachment for most people, so it'd be adding a lot of weight. Just a link might be better. But we can try it.

**Comment by flachware** [comment]
The system with the bar inside the icons we have have is highly optimized for only showing PDF and Document icons. Now that we have more icons, even composed icons, I think we are going to need a different system to indicate the states. 

We could extract the bar from the icons. Download = no bar, missing = gray bar, failed = red bar, downloaded = blue bar:

<img width="510" alt="attachments@2x" src="https://user-images.githubusercontent.com/419747/115711806-455a1f00-a374-11eb-96d8-2c260d0c03f8.png">

**Comment by flachware** [comment]
Alternatively we could use a minimized version of the icons we use in the item details:

<img width="510" alt="attachments-2@2x" src="https://user-images.githubusercontent.com/419747/115723625-75a7ba80-a380-11eb-8e6b-c1494c51d3d5.png">

**Comment by michalrentka** [comment]
The blue dot looks like a notification. I'd expect it to disappear once I tap the row. 

I'd probably go with base icon as downloaded state and add something when it's not downloaded or missing. Download could add an arrow as before. Missing could be lower opacity and/or grayscaled. Failure could have separate icon for all types.

**Comment by flachware** [comment]
Well the attachments with the dot are kind of new, you haven’t viewed them in the iOS app and the dot disappears once you do (by tapping the row).

As far as I can remember we assumed that most attachments would not be downloaded and thus we ended up to indicate the fewer attachments in the downloaded state with the blue bar.

Whatever approach we choose, I think it’s pretty clear that we can’t attach another complex state indicator icon to the attachment icons directly, a simple dot is more or less the only thing that works at this size and it happens to be a minified version of the attachment icons inside the item details. Adding the bar outside still results in a compact icon, I’m sceptical towards adding a spacious question mark or exclamation mark.

**Comment by michalrentka** [comment]
> Well the attachments with the dot are kind of new, you haven’t viewed them in the iOS app and the dot disappears once you do (by tapping the row).

How would you know the difference between downloaded and not-downloaded file if the dot disappears on tap?

> As far as I can remember we assumed that most attachments would not be downloaded and thus we ended up to indicate the fewer attachments in the downloaded state with the blue bar.

That's right. But since people are asking for functionality to download all files on sync or have screens with only downloaded files, I think it'll be more common to see many downloaded files together. @dstillman what do you think?

> a simple dot is more or less the only thing that works at this size and it happens to be a minified version of the attachment icons inside the item details

I like the dot, but I think the downloaded state needs to be shown permanently. 

I suggest we use base icon for downloaded state. Something for not-downloaded state (opacity, gray circle or something else). Progress is solved by the circle around the icon and failure could have its own icon. The missing state could be skipped completely in item list.

@dstillman does a missing file need an icon? Why don't we just hide the attachment icon if the file is missing? You'd see the attachment in item detail with the missing marker (?) and you can't do anything about it anyway.

**Comment by michalrentka** [comment]
> > How would you know the difference between downloaded and not-downloaded file if the dot disappears on tap?
> 
> > I like the dot, but I think the downloaded state needs to be shown permanently.
> 
> I fail to see the problem. The dot works like the larger icons in the item details. When you tap a row the attachment gets downloaded and thus the missing dot permanently indicates that this attachment has been downloaded, no?

Oh, I misunderstood, I thought the dot was for recently downloaded file and it would disappear after the file is opened. If it's for not-downloaded file then that's fine for me.

**Comment by flachware** [comment]
Right, it’s really what we already do in the item details, just smaller.

**Comment by dstillman** [comment]
Wait, the blue dot is for not-downloaded? I wouldn't have guessed that at all — that really feels like read/unread to me, which just doesn't seem like the right parallel to this. I think not-downloaded needs to be opacity/grayness.

> does a missing file need an icon? Why don't we just hide the attachment icon if the file is missing? You'd see the attachment in item detail with the missing marker (?) and you can't do anything about it anyway.

I think a missing file needs an icon, yes. You can do something about it: you can sync your desktop app or enable file syncing there or otherwise figure out why the file isn't online. It's more confusing for it to just be missing, as if the item doesn't have a PDF. (Really we probably need to add an error dialog on download attempt that's similar to the desktop app's file-not-found dialog that explains possible reasons the file isn't available online.)

**Comment by flachware** [comment]
Here is a version with transparency and small SF Symbols for the missing and error state:

<img width="510" alt="variant-3-1@2x" src="https://user-images.githubusercontent.com/419747/115864345-004af100-a437-11eb-9bc0-4f09a532b0ef.png">

<img width="510" alt="variant-3-2@2x" src="https://user-images.githubusercontent.com/419747/115864357-03de7800-a437-11eb-8f06-dcff9b77e22d.png">

**Comment by michalrentka** [comment]
@dstillman so do we want the transparency option?

@flachware could you send me those new small icons? For small version I only have a pdf and generic document. So I'll need snapshot, url/doi, probably even images if possible. And I guess we're keeping the big icons the same as before, so if you'll create an icon for images, I could use the big one as well, otherwise nothing needed there.

**Comment by michalrentka** [comment]
So this is almost ready. I just need those new icons (small versions for almost everything and big versions for images and plaintext).

So currently the item list shows an icon for: PDF > Snapshot > Image (jpg, png, gif) > Plaintext > DOI > URL. If icon is available and item is tapped, appropriate attachment/doi/url is opened full screen. Otherwise item metadata are opened. I implemented a simple text preview screen. Image preview was already implemented and supports images and gifs. We can improve on both of course, but they should be enough for now.

Also attachments are now processed properly (both in items list and item detail) - if API says that an attachment is compressed, I unzip it and show the unzipped content. Otherwise I try to show the content based on content type. So if attachment is a zip file originally and API doesn't say it's compressed content, I just show the share dialog for the zip (in item detail, in items list this would not show up at all).

**Comment by dstillman** [comment]
> DOI > URL

Let's reverse these. URL should take precedence (and does in client).

**Comment by flachware** [comment]
@michalrentka ok here are the icons:

16 x 16 (light and dark):
- document
- image
- link
- pdf
- plaintext
- snapshot

28 x 28 (light and dark):
- image
- link
- plaintext

I think you should have the rest, but please let me know in case i’ve missed something. The image and plaintext icons are new.  And I think the link icon looks a bit weird at the large size, I’d rather use the existing icon (web-page-linked item type icon) instead.

The SF Symbols question mark icon in the mockup above has `#888` as background at 50% opacity.

[icons.zip](https://github.com/zotero/zotero-ios/files/6415678/icons.zip)

**Comment by dstillman** [comment]
A few things (which I should've chimed in on earlier — sorry):

1) I don't love the `?` and `!` icons without any context. Is there a reason we can't go back to the badges for those?

2) A download error (switching to `?`) should show the same popup that you get in the attachments list in the item details pane. (We'll be adjusting that message to be more instructive.)

3) I worry that the transparent icons are just too hard to see. The point of these is to help you know what's going to happen when you tap, but showing washed-out version of the icon whenever you don't have the file locally, which for most people will be most of the time, makes that difficult. (The transparent icons also sort of make the gray link icon seem like it's similarly transparent.) What was the problem with the down-arrow?

**Comment by michalrentka** [comment]
Well, the problem with all the things mentioned above was pretty much that we had the blue bar representing downloaded file. This would look weird on new icons, so we started changing all states and ended up with this. 

I guess we can return to the down arrow and downloaded file would be the same icon, just without the arrow. Same with missing and error (?, ! added to the icon). The link icon doesn't need any of those and other icons should look ok with those old badges?

@flachware any comment?

**Comment by flachware** [comment]
Those icons are simply too small to add ?, arrow, and bar into them. This specifically worked for Document and PDF, but not for composed icons like the snapshot icon.

**Comment by dstillman** [comment]
We don't need a bar — just the icon without a badge once downloaded would be fine. Are we sure a badge wouldn't would work with the snapshot icon? It doesn't seem all that different from the blue dot you have mocked up above. The concern is that `?`/`!`/arrow would need to be bigger than the dot and so would cover more of the camera?

**Comment by flachware** [comment]
Yes badges with symbols in them cover too much of the camera, that’s why I decided to scale the badge down proportionally and omit the badge content, leaving a blue, gray, and red dot.

**Comment by dstillman** [comment]
I'm not sure covering the camera is a dealbreaker. Are we sure this is a problem on a retina display?

In any case, we can't use the blue dot — that looks 1) like a notification and 2) like the filled circle in the client that indicates that the file exists locally, which is the exact opposite meaning. Any other ideas?

(Also, I realize I said "I think not-downloaded needs to be opacity/grayness" above, so I'm responsible for the detour into transparency.)

**Comment by flachware** [comment]
It does not work with the current badge size, it covers the camera too much. But if we shrink the badge as much as possible it looks ok to me:

<img width="196" alt="badge@2x" src="https://user-images.githubusercontent.com/419747/117133356-6a06bb80-ada4-11eb-8342-ce5eb25789d4.png">

**Comment by dstillman** [comment]
Can we try slightly bigger? The first one is maybe a bit much, but I don't think blocking a little more of the camera than the second one is really that big a deal, even if it might be a bit less pleasing aesthetically. I guess the saving grace here is that if your eyesight is such that you can't make out the white symbol, you still see a mostly blue, gray, or red circle, but we should get every pixel we can here.

**Comment by flachware** [comment]
1px larger badge:
<img width="141" alt="badge@2x" src="https://user-images.githubusercontent.com/419747/117480172-8bf96d00-af61-11eb-9fcb-22ef120eb181.png">

**Comment by dstillman** [comment]
Let's try that in the app.

**Comment by michalrentka** [comment]
@flachware could you export those badges and icons please.

**Comment by flachware** [comment]
@michalrentka you can take the icons from the zip above. As for the badges, do you want them composed (.e.g. arrow with blue circle) or just the icons of the badges (e.g. just the arrow)? And I believe you add the white border yourself?

**Comment by michalrentka** [comment]
@flachware we're using arrow with blue circle, no border.

**Comment by flachware** [comment]
Ok, here are the icons for the badges and a positioning aid.

[badges.zip](https://github.com/zotero/zotero-ios/files/6451384/badges.zip)
![positioning](https://user-images.githubusercontent.com/419747/117646283-deb66d00-b18b-11eb-9374-9cafc42233cb.png)

**Comment by michalrentka** [comment]
@flachware and the border is 1px?

**Comment by flachware** [comment]
Yep.

**Comment by michalrentka** [comment]
I use 1.5 for the large ones.

**Comment by flachware** [comment]
I used 1px for both sizes (it’s incorrect in the positioning aid). If you think 1.5px looks better for the large icons, keep it. But for the small icons even half a pixel counts, so I think you should use 1px there.

**Comment by michalrentka** [comment]
@dstillman does this look ok now?

**Comment by dstillman** [comment]
I'm only set up to test at the moment on a non-retina display, but best I can tell, it looks good.

@flachware: Can we do something slightly different for the link icon? It's a little close to the ? gray circle at the moment. Maybe make it slightly darker?

**Comment by flachware** [comment]
Slightly darker link icon:

<img width="489" src="https://user-images.githubusercontent.com/419747/117951087-1b14d500-b314-11eb-9131-4366e08c9d7a.png">

Original link icon but orange ? badge:

<img width="489" src="https://user-images.githubusercontent.com/419747/117951139-2962f100-b314-11eb-9816-d14933510567.png">

**Comment by dstillman** [comment]
The orange is fun but I think unnecessarily distracting, so let's go with the darker link icon for now.

@michalrentka, in what situations are we displaying that badge? For linked files, we probably shouldn't display an icon at all — not sure if we are at the moment. So this would only be for files that haven't been uploaded to the server from another computer, which could indicate a problem or could just be because they're using WebDAV for file syncing. (I'm not sure a question mark is the most appropriate icon for that, particularly for the WebDAV case, but I'm not sure what the alternative would be.)

**Comment by michalrentka** [comment]
@dstillman as you said, only for attachment `imported_file` which has not been uploaded to the server (is missing the enclosure link).

**Comment by flachware** [comment]
[link.zip](https://github.com/zotero/zotero-ios/files/6467835/link.zip)

**Comment by michalrentka** [comment]
@dstillman I changed the icon. Does this seem better?
