### ISSUE TITLE
Collection positions off after sync

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#282]
https://forums.zotero.org/discussion/89133/ios-bug-collections-content-momentarily-swapped/

I haven't tried to reproduce recently, but I think I've seen something like this. Not sure if it's still an issue.

**Comment by michalrentka** [comment]
I'm not able to reproduce this. Not sure whether it was fixed or needs a special set of actions. @stakats didn't you bump into this by any chance?
