### ISSUE TITLE
Metadata table columns are misaligned

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#283]
![IMG_A741429A0AB8-1](https://user-images.githubusercontent.com/783082/117121583-c8ab4580-ad62-11eb-8bbd-2dad69f26b38.jpeg)

**Comment by michalrentka** [comment]
@dstillman I don't see the issue? Field names are aligned to the right, they all seem to be aligned to the same width to me.

**Comment by dstillman** [comment]
They're vertically misaligned.
