### ISSUE TITLE
Allow two-finger pan/zoom in highlight mode

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#286]
https://forums.zotero.org/discussion/89194/two-finger-gestures-in-highlight-mode-in-ios

Possible?

**Comment by michalrentka** [comment]
I'm talking to PSPDFKit support but most likely this won't be possible. I'll update the forum thread when I'm 100% sure.

**Comment by michalrentka** [comment]
So unfortunately PSPDFKit doesn't support this directly and custom solutions trying to mitigate this didn't work. I'll keep an eye on it to see whether they add the feature in future.
