### ISSUE TITLE
Citation functionality

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#287]
Functionality that we want:

1) A new Cite → Citation Styles section in the settings that shows you installed styles (with same bundled defaults as the client) and lets you add more via a search (pulling from https://www.zotero.org/styles-files/styles.json, accepting gzip encoding so that it's not >2 MB) and removed installed ones. See Preferences → Cite → Styles in the client for reference. (That pulls up the [Zotero styles page](https://www.zotero.org/styles), but for now we can use a simple search as on [ZoteroBib](https://zbib.org).)
    - We can do this later, but eventually we should add manual installation of styles from the Files app, ideally with [csl-validator.js](https://github.com/zotero/zotero/blob/master/resource/csl-validator.js) for validation, as [in the client](https://github.com/zotero/zotero/blob/d3a78982f01c3aad704e67e6c6b09cf54d33d8fb/chrome/content/zotero/xpcom/style.js#L243-L261). Already running in a worker, so hopefully will be pretty straightforward.

2) A new Quick Copy section in the settings similar to Preferences → Export → Quick Copy in the client, allowing you to select a default format (currently limited to styles), locale, and "Copy as HTML", which determines whether it puts the HTML on the clipboard as HTML or as plain text (the latter resulting in actual HTML markup when you paste). When "Copy as HTML" is disabled, citeproc-js's HTML output is set as HTML and its text output is set as text, so you get rich text or not as appropriate depending on your paste target.

3) Item context menu → Copy Citation and Copy Bibliography options. Copy Citation should open a dialog similar to Copy Citation on ZoteroBib, with locator, Omit Author, and a preview. Copy Bibliography should copy a bibliography entry for the selected item directly to the clipboard.

4) Some way to trigger the above options for multiple items via Select. We're a bit limited in space in the bottom toolbar for multi-item selection, and we'll want Export options later, so one option would be to have a single Share button that opened an intermediate popup similar to the share popup in the Twitter app that would let you pick from among various options, some of which would take to the system Share sheet. We'll need to play with this UI a bit, but I'm imagining a multi-step process where you choose between Citations/Bibliography/Export → citation/style/locale/export options → clipboard or share sheet.

    - The idea is that you would use the context-menu options for going and back and forth copying into a word processor with less friction, but if you wanted to text someone a bibliography or email them a BibTeX file (eventually), you'd go this route, where you could choose specific options for this output.
    - The dialog would remember your last-used settings.
    - We can move Duplicate in the bottom toolbar to the context menu, since it doesn't work on multiple items anyway, and use the space for a share button.

Miscellaneous details:

- Installed styles should update via the repo along with translators. Since installed styles will vary, those aren't sent by default. Instead, we [send a list](https://github.com/zotero/zotero/blob/d3a78982f01c3aad704e67e6c6b09cf54d33d8fb/chrome/content/zotero/xpcom/schema.js#L1590-L1606) of installed style ids, timestamps, and rel="self" URLs in the repo request, and the repo sends back modified styles.
- Locale files, which need to be passed to the citation processor, should come from https://github.com/citation-style-language/locales as a submodule. The locale list comes from [locales.json](https://github.com/citation-style-language/locales/blob/master/locales.json) in that repo, using the native translations. We can update this submodule manually.
- Some styles have a default locale, [specified by a `default-locale` attribute](https://docs.citationstyles.org/en/stable/specification.html), that should disable the locale list with a specific locale selected. If the locale doesn't exist, the code itself should be added to the list, though the actual fallback order when calling the citation processor should be `default-locale` → last-selected locale → OS locale. A locale set by the style shouldn't change the last-selected locale, so if you select another style the menulist should become active again with your previous selection.
- The citation processor needs [CSL-JSON](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html), which is different from Zotero API JSON. This is complicated. We'll leverage existing code for this, but for the moment, let's do all of the above but make it completely nonfunctional by subbing in some hard-coded CSL-JSON in place of actual JSON for selected items, and we'll get you some JS that you can add to the webview that will convert API JSON into CSL-JSON.

Various other minor details, but we'll deal with those once this is generally working.

**Comment by dstillman** [comment]
Bundled styles should be a submodule of [this repo](https://github.com/zotero/bundled-styles/), which we'll also update manually.

Default should be chicago-note-bibliography

**Comment by michalrentka** [comment]
@dstillman here's preview for the cite/export screen for multiple selected items:
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2021-07-01 at 15 18 51](https://user-images.githubusercontent.com/1022956/124131058-b9edc000-da7f-11eb-81d4-b2225ffbac3d.png)

When bibliography is not supported:
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2021-07-01 at 15 24 35](https://user-images.githubusercontent.com/1022956/124131834-76478600-da80-11eb-94aa-7d9e7bbe07eb.png)

And when export is supported with additional picker (will need better design, but the point is there):
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2021-07-01 at 15 22 53](https://user-images.githubusercontent.com/1022956/124131620-46987e00-da80-11eb-88aa-ac28611f5404.png)

**Comment by dstillman** [comment]
One quick thing: Output Mode should go below Language, since it's dependent on the style list. (And then I think we can remove "This style doesn't support…" text.)
