### ISSUE TITLE
Add "Download"/"Remove Download" to item context menu

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#291]
"Download" should download the primary file, equivalent to tapping.

"Remove Download" should remove all downloaded files, including secondary files. Ideally it would only appear if there's a downloaded file, but if we can't check that easily for secondary files it could appear only when the primary file is downloaded.

Ideally you'd be able to do these on multiple items at once, but we don't really have room in the bottom toolbar for even a "…" button. (To recap, the plan in https://github.com/zotero/zotero-ios/issues/287 is to add a Share button after removing "Duplicate", but that doesn't help here.) Is it possible to just show a context menu on multiple items? You can select and drag, so any reason that wouldn't work for a context menu as well?

**Comment by michalrentka** [comment]
iOS doesn't support context menu for multiple selected rows unfortunately, so all actions will have to be in the toolbar. We can fit 5 actions there or we can add "..." and show action sheet (image below) for remaining actions. I'll add "Download" and "Remove Download" actions for single item and we can decide how to do it for multiple items later.

![](https://images.squarespace-cdn.com/content/v1/52428a0ae4b0c4a5c2a2cede/1579859219147-JODXOAP9W645JS9P6HGF/ios-action-sheet-simulator.png)

**Comment by dstillman** [comment]
Another request for multiple items here: https://forums.zotero.org/discussion/comment/398798/#Comment_398798

For searches, I forgot there that you said we couldn't do a context menu for multiple items…
