### ISSUE TITLE
Allow changing annotation colors via main popup screen

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#296]
https://forums.zotero.org/discussion/89796/ipados-beta-ux-choice-have-all-annotation-colors-visible-in-color-palette-all-the-time

I think it makes sense for this to be in the main screen instead of the Edit Annotation screen.

**Comment by michalrentka** [comment]
I don't think he means colour switching for existing annotation, but colour picker for annotation creation. He wants to have the whole colour palette visible in navigation or toolbar. I guess we could have a switch in settings which would show the whole colour palette either in toolbar on bottom or floating on side.
