### ISSUE TITLE
Remove bundled style locales

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#305]
Added in https://github.com/zotero/zotero-ios/commit/b2fb865bccdd49533ff948abdc4cee9bb8db49e0

Not sure if this was a mistake, but it shouldn't be necessary to bundle copies of these.

And let's rebase to remove from the history — no reason for these to take up space in the log.

**Comment by michalrentka** [comment]
@dstillman where do I get those locales if I don't bundle them? The citeproc-js example downloads appropriate locale, so I thought instead of downloading it each time I can just bundle them. Are they already bundled anywhere?

**Comment by dstillman** [comment]
It should just be a submodule.

https://github.com/citation-style-language/locales

**Comment by michalrentka** [comment]
@dstillman it is a submodule, but the submodule contained some unnecessary files. So I added the submodule to root of the project and I copy only xml and json files to Bundled folder. So only those get bundled with the app. If I added the whole submodule to the Bundled folder I couldn't pick which files I wanted to bundle and which to ignore. Appropriate files are copied from the submodule to Bundled folder on each build.

**Comment by dstillman** [comment]
So why not just add those files to .gitignore? If they're build artifacts, they shouldn't need to be checked in.

**Comment by michalrentka** [comment]
In that case I can also remove styles and translators, those are generated the same way. I can leave only timestamp.txt and schema.json.

**Comment by dstillman** [comment]
Not totally sure what you mean. I'm not seeing style and translator files checked in anywhere.

**Comment by michalrentka** [comment]
Yeah translators are ignored, but I forgot about styles and locales (in the citation branch, not in master).
