### ISSUE TITLE
Add Delete Annotation to main annotation view

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#310]
(I thought we had an issue for this but I can't find it.)

https://forums.zotero.org/discussion/90424/deleting-annotations-in-ios-iphone-and-ipad-versions

We've received a bunch of feedback that (even leaving aside the problems from https://github.com/zotero/zotero-ios/issues/307) it takes too many steps just to delete an annotation. I think we need to add that option to the main view, similar to Calendar (which puts Delete Event right in the popup, even though it's also in the Edit view).

**Comment by michalrentka** [comment]
I added the delete button into the popover itself and I also added swipe to delete in sidebar.

**Comment by dstillman** [comment]
Did this change? "Delete Annotation" appears for me in the Edit Annotation view, not the main annotation view. (Swiping to delete still works in the sidebar, though.)

**Comment by dstillman** [comment]
Oh, maybe was added to the "…" menu from the annotations sidebar, but not the popup from the PDF view? It should go in there too.
