### ISSUE TITLE
Assigned tags don't appear in annotation popup until popup is reopened

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#311]
https://forums.zotero.org/discussion/90444/tagging-in-ios-beta

I can reproduce this.

**Comment by dstillman** [comment]
(I can't reproduce the second person's problem, though, at least in 127.)

**Comment by michalrentka** [comment]
I used wrong # in 5f16379d6872a3766126c6b91a5aedfe3e52838a but it's a fix for this issue. I think I was able to fix the second problem as well.
