### ISSUE TITLE
External links to items

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#316]
https://forums.zotero.org/discussion/89272/ios-beta-feature-request-deep-linking-i-e-zotero-select-schema-to-open-in-ios-zotero-app
https://forums.zotero.org/discussion/93588/zotero-protocol-on-ipad-beta-feature-request

Have to decide whether we want to use a [custom scheme](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app) and/or [universal links](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content).

Unclear if a custom schema works with slashes such that existing `zotero://select` links could work or if only `zotero:select` would work. Only `zotero:select` would be much less useful, since these links would mostly be coming from notes in third-party tool synced with other platforms.

Universal links probably don't make a lot of sense for us at this point. On the desktop they'd just take you to the website, which we don't really want. They'd require us to display items not in your library, which is a whole other thing. And we want to support things like [annotation selection](https://github.com/zotero/zotero-ios/issues/315) that aren't yet supported in the web library.

**Comment by cweniger** [comment]
I *think* that a custom schema should work with slashes, most examples that one can find, like https://useyourloaf.com/blog/launching-ios-apps-with-a-custom-url-scheme/, use "://". I suppose the slashes are optional.

Would be awesome to have this implemented soon, although I fully understand if you have other priorities. Actually just linking to pdfs (via open-pdf), and the ability to jump to a specific page, would be more than enough to jump back to specific annotations.

**Comment by michalrentka** [comment]
@dstillman custom scheme works with slashes and without them. So both `zotero://command` and `zotero:command` would work. What commands/urls do we want to support?

**Comment by dstillman** [comment]
`zotero://select` to select items in the items list (which could include child items, so we'd have to select the parent, I guess) and `zotero://open-pdf` to open a PDF in the reader.

https://github.com/zotero/zotero/blob/966bee275c3f58099c275b9821c214c35c46a2a8/components/zotero-protocol-handler.js#L1106-L1112

https://github.com/zotero/zotero/blob/966bee275c3f58099c275b9821c214c35c46a2a8/components/zotero-protocol-handler.js#L1106-L1112

**Comment by cslaviero** [comment]
Hi, any changes about this issue? I've got some use cases for my workflow that need it and it would be great to have it working 😁

**Comment by grothen** [comment]
![CleanShot 2022-09-18 at 21 19 14](https://user-images.githubusercontent.com/3252576/190904198-9c850e51-605f-4bcd-92b0-f19a816730b3.png)
https://forums.zotero.org/discussion/99398/links-to-pdfs-work-on-mac-but-not-on-ios#latest
