### ISSUE TITLE
Citation support: Raw HTML markup copied to clipboard as plain text

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#319]
When copying a citation, the raw HTML markup ends up in the output. That might be an optional mode later, similar to "Copy as HTML" in the client's Quick Copy settings, but by default it should copy plain text and HTML as separate flavors, with the HTML marked as rich text, so when you paste into something that supports rich text you get rich text and otherwise you get plain text. (I assume this is possible on iOS, the same as on other platforms.) citeproc-js has 'text' and 'html' modes.

**Comment by dstillman** [comment]
This doesn't seem to be fixed. If I paste a copied bibliography in notes, I'm still getting raw HTML.

**Comment by michalrentka** [comment]
@dstillman @tnajdek I'm passing the `text` format to the `getBibliography` function defined in `citeproc-starter-pack.js`. The result is returned by `format === 'html' ? formatBib(bib) : bib[0].bibstart+bib[1].join('')+bib[0].bibend`, where `bibstart`, `bibend` and `bib[1]` are all HTML outputs. It seems the `makeBibliography()` function always generates HTML output. I'm checking the citeproc-js docs but I don't see a way of changing the HTML format to something else in bibliography?

**Comment by tnajdek** [comment]
@michalrentka `makeBibliography` in the example lacked support for rendering plain-text bibliography, I've fixed it now.

**Comment by michalrentka** [comment]
@tnajdek thanks! Seems to be working now.

**Comment by dstillman** [comment]
OK, sounds like this will fix #329 then, too.
