### ISSUE TITLE
Translators not updating

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#325]
For some reason I don't have recent translators in the app. We should be checking for updates to translators and installed styles once a day (in addition to anything we're doing for WebSocket notifications, which I can't remember).

**Comment by dstillman** [comment]
Any recent translator would do. E.g., https://www.currentaffairs.org/2021/08/tenant-organizing-in-washington-d-c-and-beyond saves as a webpage instead of a magazine article. Same result on two different devices. (Actually I get Embedded Metadata on one and DOI on another, so not sure what that's about, but doesn't have the new translator on either.)

**Comment by michalrentka** [comment]
@dstillman it looks like the repo request is not returning any translators for me. For example in current build this is called https://repo.zotero.org/repo/updated?m=3&last=1616016826&version=1.0-iOS with some styles included and I only get back styles, no translators. The url without styles returns only `currentTime`. Did I break something here? Are there supposed to be other parameters?

**Comment by dstillman** [comment]
Oh, no, this just never would've worked — the repo wasn't returning anything for version strings like that.

Should work now.

We'll need to update bundled translators, since people will have missed earlier updates. It looks from https://github.com/zotero/zotero-ios/blob/master/bundled/translators/timestamp.txt like we haven't done that since March? Technically it doesn't matter, because (when this is working) new clients will download any updates at startup, but now that we have many more translators changing every day, we'll want to updated bundled translators more often, since otherwise every client would download a huge number of translators at first run. Once we're out of beta, we'll just want to do it with every release, which is what I do for the desktop.

**Comment by michalrentka** [comment]
The API seems to work well now. I'll update bundled translators on next build release.
