### ISSUE TITLE
Citation support: Add formatting to copied bibliographies

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#329]
Various inline CSS needs to be added to HTML bibliographies from the citation processor. (It's handling the parameters defined [here](https://citeproc-js.readthedocs.io/en/latest/running.html#makebibliography).) It looks like citeproc-starter-pack.js [has support for this](https://github.com/zotero/zotero-ios/blob/b998c62634a81a618dcaa2a87695f4f7288e1b84/Zotero/Controllers/Citation/citation/citeproc-starter-pack.js#L93), but I'm not seeing any CSS in the raw HTML that's ending up in notes from https://github.com/zotero/zotero-ios/issues/319, so maybe it's not being applied?

Technically `text` mode should also use `bibstart` and `bibend`, as shown in the client's [`makeFormattedBibliography()`](https://github.com/zotero/zotero/blob/9738d20558c13770ea0d58524c226a5ba60fe60d/chrome/content/zotero/xpcom/cite.js#L135), though I don't know if those are ever non-empty.

**Comment by michalrentka** [comment]
@dstillman when you export a bibliography and choose "Save as HTML" it produces HTML with some style in the div:
```
<div class="csl-bib-body" style="line-height: 1.35; margin-left: 2em; text-indent:-2em;">
  <div class="csl-entry">Westphal, Oliver and michal rentka. “A Framework for Generating Diverse Haskell-IO Exercise Tasks.” <i>ArXiv:2008.12751 [Cs]</i>, August 28, 2020. http://arxiv.org/abs/2008.12751.</div>
</div>
```

If you choose "Copy to Clipboard" or use "Copy Bibliography" I pass `text` format to the `getBibliography` function and it does what I described in #319.
