### ISSUE TITLE
Citation support: Dependent styles don't work

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#330]
https://github.com/zotero/zotero-ios/issues/324 fixed the error installing dependent styles, but they still don't work for me — trying to cite with, e.g., Tropical Doctor, the process just hangs. (That should also be fixed so that we throw a proper error if something goes wrong, since right now it will just say "Generating Bibliography" forever.)

**Comment by tnajdek** [comment]
@michalrentka you need to check if style is independent and if it isn't, fetch parent style and provide that instead.

**Comment by dstillman** [comment]
1) They let people choose a style by name without knowing that, say, the journal just says to use another style.

2) They can override `default-locale`. So that's the one thing you need to pass in.

From the [documentation](https://docs.citationstyles.org/en/stable/specification.html#dependent-styles):

> A dependent style is an alias for an independent style. Its contents are limited to style metadata, and doesn’t include any formatting instructions (the sole exception is that dependent styles can specify an overriding style locale). By linking dependent styles for journals that share the same citation style (e.g., “Nature Biotechnology”, “Nature Nanotechnology”, etc.) to a single independent style (e.g., “Nature Journals”), there is no need to duplicate formatting instructions.

And see slightly down from there for another mention of the `default-locale` override for dependent styles.

**Comment by dstillman** [comment]
@tnajdek: You should actual confirm that you're overriding default-locale for dependent styles in ZBib.
