### ISSUE TITLE
Make Quick Copy a top-level settings section

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#331]
The Export row is broken for me in 133, but since we have nothing else to put in Export and it's confusing, let's make Quick Copy a top-level section.

**Comment by michalrentka** [comment]
@dstillman I'm not sure what you mean here. Do you want me to rename "Export" to "Quick Copy"?

**Comment by dstillman** [comment]
Yes — and presumably remove the "Quick Copy" header in the content pane, which would become redundant.
