### ISSUE TITLE
Don't zoom Cite settings

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#332]
I assume this was to show long citation style names, but I think it's too weird.

If we want more space for settings panes, it seems like we should copy the Settings app layout and use a two-column layout.

**Comment by michalrentka** [comment]
@dstillman I changed it so that it doesn't resize. Do we want to keep it for cite search or not? When you tap "Get additional styles" it shows a screen with all styles and search bar in full screen.

**Comment by dstillman** [comment]
I'm not sure it's necessary for "Get additional styles", but it's fine — it feels more like opening a special browsing pane, and it's a pretty big list.

We're still zooming "Default Format" in the Quick Copy prefs, though, and we should remove that.
