### ISSUE TITLE
Citation support: "Copy as HTML" doesn't copy HTML

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#338]
1) Select APA 7th in Quick Copy settings and enable "Copy as HTML"
2) Select Copy Bibliography from context menu
3) Paste somewhere

Plain text is pasted rather than HTML markup

**Comment by dstillman** [comment]
Similarly, if I go to Share, select "Bibliography" and "Save as HTML", and then press Copy in the native share sheet, I get the same plain text. I would expect that to also be HTML markup.

**Comment by dstillman** [comment]
Yeah, it's copying HTML as HTML — so, e.g., I get italics in a rich-text field. It should be copying HTML markup as text.

**Comment by dstillman** [comment]
Actually, for Quick Copy, I'm just getting plain text with no formatting.

When using "Save as HTML" and then "Copy" from the Share sheet, I get HTML as HTML. Whether that's correct is sort of a matter of perspective. If you choose "Save as HTML" and save to a file, you're going to get an HTML text file on disk. If you instead press "Copy", you're copying what was going to be stored in the file, but are you copying it as plain text or as HTML?

**Comment by michalrentka** [comment]
I fixed the "Copy Bibliography" context button, I forgot to include the "Copy as HTML" option there and it always generated plain text.

The share sheet on the other hand I have no control over it, iOS handles that by itself. For example when I copied from the share sheet and pasted to Notes app, it included the whole html file as attachment there.
