### ISSUE TITLE
Hang sharing citation for note style

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#342]
1. Install "History and Theory" style
2. Select magazine article (I used [this one](https://www.theatlantic.com/health/archive/2014/09/the-evil-reign-of-the-red-delicious/379892/))
3. Share → select "History and Theory" → select Citations → select either Save as HTML or Copy to Clipboard
4. Tap Done

It hangs for me, with a spinner over the dialog.

Along with fixing this, we should make sure we're catching all potential errors and showing an error message (with the underlying error either included or logged).

**Comment by dstillman** [comment]
Oh, this is actually a note style, so copying citations really means copying notes — in "Create Bibliography from Items" in the desktop app, "Citations" actually changes to "Notes", and we should do the same here for consistency.

I believe the relevant code in the desktop app is [here](https://github.com/zotero/zotero/blob/f274323478bbc0fb26aa876a832197add76891d8/chrome/content/zotero/xpcom/cite.js#L94). I haven't looked at the starter pack, but @tnajdek or @adomasven may be able to advise on what needs to change there for this.

**Comment by dstillman** [comment]
You can see the style source here:

https://www.zotero.org/styles/history-and-theory?source=1

The `class="note"` indicates it's a note style and that you should show "Notes" instead of "Citations" and use the different handling.

**Comment by dstillman** [comment]
Oddly, Copy Citation does work with this style selected.

**Comment by dstillman** [comment]
Or, no, sorry, for copying citations, it's `previewCitationCluster()` on citeproc-js.

For a bibliography, it's the code linked above, but I'll create a separate issue for that.

**Comment by michalrentka** [comment]
> 1. Install "History and Theory" style
> 2. Select magazine article (I used [this one](https://www.theatlantic.com/health/archive/2014/09/the-evil-reign-of-the-red-delicious/379892/))
> 3. Share → select "History and Theory" → select Citations → select either Save as HTML or Copy to Clipboard
> 4. Tap Done
> 
> It hangs for me, with a spinner over the dialog.
> 
> Along with fixing this, we should make sure we're catching all potential errors and showing an error message (with the underlying error either included or logged).

The app is not hanging for me with the same style and article. Not sure which build you tested this with. 

I'm handling and showing errors which I can catch. But if there is some javascript issue inside webkit that doesn't throw exception, the webview just doesn't report anything to me. If the javascript code includes `Zotero.debug(...)` messages those should at least show up in our logs. I can add a timeout there, but it's easy to just close the window in case it takes too long, so I don't think it's necessary.

**Comment by michalrentka** [comment]
> "Citations" actually changes to "Notes"
> for copying citations for a note style, it's still just previewCitationCluster() from citeproc-js, and it should be the same as Copy Citation in the context menu

So the only difference for a note style is changing "Citations" to "Notes" in the UI? Should the "Copy Citation" in context menu change to "Copy Note" as well?

**Comment by dstillman** [comment]
Working now

**Comment by dstillman** [comment]
> Should the "Copy Citation" in context menu change to "Copy Note" as well?

No, I think "Note" is too confusing out of context. We still say "Copy Citation" in the Edit menu on desktop.
