### ISSUE TITLE
Ink annotations: Label for thickness slider

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#349]
Both when you press and hold on the annotation tool and when editing an ink annotation later

Also, is "pt." the right unit? Should there be any unit? "pt." doesn't really add much value in my mind.

**Comment by michalrentka** [comment]
pt should be right unit, it's not pixels or anything else. PSPDFKit have this in their sample app, so I added the same unit. The value is debatable. It's always good to see the unit, but in this case it's probably not that important. I'll get rid of it and you'll see how it looks.
