### ISSUE TITLE
Ink annotations: "Done" button doesn't work

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#350]
1. Create ink annotation
2. Tap on annotation

On my 12 mini, Done is inactive. I can only close the popup by sliding from the top.

**Comment by dstillman** [comment]
Oh I guess this is an issue with all annotations?

https://forums.zotero.org/discussion/91956/issues-with-annotations-while-reading-pdfs-in-ios-beta

**Comment by dstillman** [comment]
(And some other comments there that may or may not be related.)

**Comment by michalrentka** [comment]
I fixed the done button. The landscape not being swipable seems to be iOS thing. And I don't know about his sync issues. Can you reproduce that?

**Comment by michalrentka** [comment]
So apparently there was no sync issue, just the text was black on dark background and he couldn't see it. This should be fixed in next build.
