### ISSUE TITLE
Sync upload error due to missing attachment

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#353]
https://forums.zotero.org/discussion/91857/ios-beta-sync-failed

> UploadAttachmentSyncAction: missing attachment

A few of these. Not sure if they're all related, but we should deal with them somehow.

**Comment by dstillman** [comment]
Another report: https://forums.zotero.org/discussion/92373/sync-failed-failed-api-response-no-response

**Comment by michalrentka** [comment]
Hopefully with previous changes to background uploads these should be resolved.
