### ISSUE TITLE
WebDAV: "Verify Server" should be disabled when no URL, username, or password

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#365]

**Comment by dstillman** [comment]
And then the separate errors for each of those fields being empty could probably be removed.

(I'm not actually sure why the desktop client allows you to click Verify Server when any of those fields are empty.)

**Comment by michalrentka** [comment]
They can't really be removed. If you enable webdav but don't verify, the webdav is still enabled. So when you do something in the app I still try to verify server first and then I find out that something is missing. I can of course have just one error when something is missing.

**Comment by dstillman** [comment]
OK, that's fine — I can populate those errors with the right text.
