### ISSUE TITLE
WebDAV: Use different control for HTTP/HTTPS picker?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#368]
The current control takes up a huge space and also doesn't close automatically after selection. (I couldn't actually figure out how to close it until I accidentally tapped back on the "http:" in the URL line.)

Is there another control we can use that would show both options in a more reasonable amount of space and close on select?

**Comment by dstillman** [comment]
(It also currently seems to open the picker even when tapping on part of the URL field.)

**Comment by michalrentka** [comment]
I changed it to the same picker as where you pick between zotero and webdav.
