### ISSUE TITLE
WebDAV: Verification error "The operation couldn't be completed. (Zotero.AFResponseError error 1.)"

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#372]
I entered `http://` and `foo.local` and got this error. I would expect to get "Could not connect to WebDAV server". (Maybe that's not currently shown for a DNS lookup failure?)

**Comment by dstillman** [comment]
Same for an inaccessible IP address, after a long (30-second?) delay.

**Comment by michalrentka** [comment]
The 30 second delay is a timeout. For some reason the http request doesn't respond immediately but waits for a timeout. Sometimes it doesn't though and I can't seem to be able to control it. I can lower the timeout if needed.

I added a cancel button though and I'll add the error message for timeouts.

**Comment by dstillman** [comment]
15 seconds seems a bit more reasonable, if we can change it.
