### ISSUE TITLE
WebDAV: Share extension and app upload .prop file but no .zip

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#374]
Saving the Bitcoin PDF from the share extension:

```
172.17.0.1 - - [04/Nov/2021:08:37:35 +0000] "GET /zotero/S37JLNQD.prop HTTP/1.1" 401 381 "-" "ZShare/161 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - test [04/Nov/2021:08:37:35 +0000] "GET /zotero/S37JLNQD.prop HTTP/1.1" 404 218 "-" "ZShare/161 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - - [04/Nov/2021:08:37:35 +0000] "POST /zotero/ HTTP/1.1" 401 381 "-" "ZShare/161 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - test [04/Nov/2021:08:37:35 +0000] "POST /zotero/ HTTP/1.1" 404 205 "-" "ZShare/161 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - test [04/Nov/2021:08:37:35 +0000] "PUT /zotero/S37JLNQD.prop HTTP/1.1" 201 193 "-" "ZShare/161 CFNetwork/1240.0.4 Darwin/20.6.0"
```

No ZIP was uploaded.

When I opened the app, the icon showed the gray question mark, and tapping it turned that to the red exclamation mark:

```
172.17.0.1 - - [04/Nov/2021:08:38:28 +0000] "GET /zotero/S37JLNQD.zip HTTP/1.1" 401 381 "-" "Zotero/161 CFNetwork/1240.0.4 Darwin/20.6.0"
172.17.0.1 - test [04/Nov/2021:08:38:28 +0000] "GET /zotero/S37JLNQD.zip HTTP/1.1" 404 217 "-" "Zotero/161 CFNetwork/1240.0.4 Darwin/20.6.0"
```

Also, why is there a POST in there? There shouldn't be a POST as part of WebDAV.

**Comment by dstillman** [comment]
Sorry, created this in the wrong repo.

**Comment by michalrentka** [comment]
@dstillman the POST request should be the upload of file. I'm making a multipart form post request to webdav to upload the file. I reused background and local uploaders for this, where both work like that. This worked fine for me, but I guess your server doesn't support it?

So should all write requests to WebDAV be PUT? One downside would be, that I can't track progress for this upload, in case we wanted to show that in UI sometime. I'll also have to check whether background uploads will work fine, but I'm quite sure they will.

**Comment by michalrentka** [comment]
I updated webdav to use only PUT requests and I'm making a new build, let me know whether that works for you.

**Comment by dstillman** [comment]
Yeah, this should definitely be PUT. A multipart form upload to WebDAV isn't a thing I've ever heard of — I'm surprised you found a server where that worked. (I'm just testing with a basic Apache install.) POST wasn't in the original WebDAV spec at all, and while it's specified as an extension in [RFC 5995](https://datatracker.ietf.org/doc/html/rfc5995), many servers wouldn't support it, it's for a specific purpose (server-assigned URLs) that's not relevant here, and it doesn't use multipart form anyway.

I'll test with the new build.
