### ISSUE TITLE
400 error for file upload authorization

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#375]
https://forums.zotero.org/discussion/92781/sync-in-zotero-ios-beta

```
(+0000086): Sync: uploadAttachment(Zotero.AttachmentUpload(libraryId: Zotero.LibraryIdentifier.custom(Zotero.RCustomLibraryType.myLibrary), key: "27WMUHSK", filename: "Safari - Jul 29, 2021 at 6_18 PM.pdf", contentType: "application/pdf", md5: "<null>", mtime: 0, file: Zotero.FileData(rootPath: "/private/var/mobile/Containers/Shared/AppGroup/11A283FD-8C74-42DC-B619-43652F282664", relativeComponents: ["downloads", "custom_my_library", "27WMUHSK"], name: "Safari - Jul 29, 2021 at 6_18 PM", ext: "pdf", mimeType: "application/pdf"), oldMd5: Optional("<null>")))

(+0000003): HTTP POST https://api.zotero.org/users/5937094/items/27WMUHSK/file
[ERROR] Zotero(+0000136): AuthorizeUploadSyncAction: can't authorize upload - responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(code: 400))
[ERROR] Zotero(+0000000): AuthorizeUploadSyncAction: key=27WMUHSK;oldMd5=<null>;md5=<null>;filesize=1665267;mtime=0

(+0000000): Sync: aborted

(+0000001): Error: apiError("No response")
```

Not sure what's causing this, and I suspect the "No response" is also wrong — there should pretty much always be a response body for a 400. Based on the response size in the server logs, my best guess is that it's an `If-Match` header with an invalid ETag:

```php
if (!empty($_SERVER['HTTP_IF_MATCH'])) {
	if (!preg_match('/^"?([a-f0-9]{32})"?$/', $_SERVER['HTTP_IF_MATCH'], $matches)) {
		$this->e400("Invalid ETag in If-Match header");
	}
```

But I can't be sure.

**Comment by dstillman** [comment]
Another report in that thread with the same response size

**Comment by michalrentka** [comment]
@dstillman the response is "Invalid ETag in If-Match header" as you found. It's actually there in the log. Not sure why I show "No Response" here, that's an easy fix.

Though the weird part is how I got a md5="<null>" (actual string). This value is taken from the md5 field of item. Since it's up for upload the item was created on the device with wrong md5. I'll ask for the files they added to the app and still hopefully have them somewhere.

**Comment by michalrentka** [comment]
Logs should show appropriate responses now, if there was any body included. I also "accidentally" got the md5="<null>" issue while testing, unfortunately I was not able to debug it yet. But the issue doesn't seem to occur when the upload is created, but rather something happens during/after upload, alters the md5 field and then we have this weird behavior. I'll keep trying to reproduce and fix this.

**Comment by michalrentka** [comment]
Related to #400 and #406.
