### ISSUE TITLE
Don't try to download linked files

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#384]
https://forums.zotero.org/discussion/92979/ios-webdav-the-attached-file-could-not-be-found

> AttachmentDownloader: failed to download attachment 988RQKJM, custom(Zotero.RCustomLibraryType.myLibrary) - incompatibleAttachment

We could just make linked files not active at all, but maybe it's clearer to keep them active and just show an error message saying that linked files aren't supported on iOS?

**Comment by dstillman** [comment]
Actually, we should just ignore linked files completely in the items list — so don't consider them when choosing an icon or tap action — but then show a clearer error if they try to tap on them in the details pane. (Maybe we're already doing the former and this report is only about the latter.)

**Comment by michalrentka** [comment]
They were mostly hidden from items list, there was a little bug, which allowed to show linked file icon in items list when it was an attachment item without a parent, so I fixed that. I also added a better error message when tapping linked file.
