### ISSUE TITLE
Can not access the webdav address with port numbers, such as http://www.abc.com:5005/zotero

### ISSUE THREAD

**Issue by xinzhangseu** [zotero/zotero-ios#387]
I would like to access the webdav storage from a nas.  The webdav address will have the portnumbers, but the app can not connect to the webdav server of the address like http://www.abc.com:5005/zotero/.

**READ THIS BEFORE CREATING AN ISSUE**

Zotero does not use GitHub Issues for bug reports or feature requests.

Please post all such requests to the Zotero Forums at https://forums.zotero.org, where Zotero developers and many others can help. For confirmed bugs or agreed-upon changes, Zotero developers will create new issues in the relevant repositories.

Development questions involving code, APIs, or other technical topics can be posted to the zotero-dev mailing list at http://groups.google.com/group/zotero-dev.

See https://www.zotero.org/support/zotero_support for more information on how Zotero support works.

**Comment by dstillman** [comment]
Please post all support requests to the forums (as it says in the text above).

This isn't about port numbers. We're not able to support http:// on iOS:

https://forums.zotero.org/discussion/comment/393886/#Comment_393886
