### ISSUE TITLE
Cannot verify WebDAV server

### ISSUE THREAD

**Issue by tobson** [zotero/zotero-ios#389]
I've been using WebDAV sync on Zotero's desktop app for years. When I try to set this up in exactly the same way on the iOS app I get the following error message when I try to verify the server.

`The operation couldn't be completed. (Zotero.AFResponseError error 1.)`

**Comment by dstillman** [comment]
Please post all support requests to the forums (but not this, because there are many threads on this and we're working on a fix).

**Comment by tobson** [comment]
My mistake. The forum obviously has superior bug-tracking capabilities...
