### ISSUE TITLE
WebDAV: Download doesn't work if ZIP contains different filename from DB?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#393]
https://forums.zotero.org/discussion/93079/ios-webdav-unable-to-display-document

I didn't test this, but in this case the ZIP contains FluSense.pdf, but the database has a normal metadata-renamed file. Not sure how that happened — maybe the file was uploaded before a parent item was created, and the file was never reuploaded with a new filename?

If there's a ZIP with a single file, the app should rename the extracted file to the filename in the database. It doesn't need to reupload the file, since other clients should handle the ZIP the same way.

(I'm guessing this is the problem in this thread behind `AnnotationsViewController: trying to reload empty document`, but it's possible there's some other problem.)

**Comment by michalrentka** [comment]
Fixed, I also added a check after download and unzip to see whether the file really is in place. So you shouldn't be seeing those screens where PDF reader tries to open but there's nothing to open.
