### ISSUE TITLE
WebDAV: Restore support for Digest authentication

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#394]
https://forums.zotero.org/discussion/93064/ios-webdav-doesnt-work-with-digest-authentication

Hard-coding the Authentication header for Basic Auth breaks Digest authentication, which we supported in earlier builds and which the desktop app supports. We should figure out what the actual problem was with the 401s in the earlier builds — I think the weirdly-cased `Www-Authenticate` in the logs may have been a red herring — and come up with a proper fix, which ideally will let us rely on the system's built-in support for Digest Auth.

**Comment by michalrentka** [comment]
So hopefully both basic and digest auth should work now. I tested with my own server and also with box.com and pcloud. All worked for me, hopefully they will work for others as well.
