### ISSUE TITLE
Save ScienceDirect PDFs via browser

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#395]
https://forums.zotero.org/discussion/93265/ios-beta-share-from-safari-save-to-zotero-grayed-out

This is likely the same issue we fixed in https://github.com/zotero/zotero/pull/2248 — ScienceDirect PDFs now sometimes require a browser-based redirect to serve PDFs, so the PDF URL returned from the translator can't be downloaded directly.

The desktop app samples downloaded PDFs to ensure that they're valid and discards them if not (which I think we do on iOS too, right?). With this change, if a downloaded PDF isn't a PDF and the URL includes `://www.sciencedirect.com`, Zotero loads the URL in a browser, watches for `Content-Type: application/pdf`, and saves the resulting file. Not sure if we did this yet on desktop (@adomasven?) but there probably should also be some sort of timeout in case the page never redirects properly to a PDF.

`https://zotero-static.s3.amazonaws.com/test-pdf-redirect.html` can be used in a test to confirm that this works.

Separately, we should figure out exactly why this is hanging currently and make sure that doesn't happen. Assuming this is the same issue, it would be a PDF URL that serves some combination of 3xx and 200 text/html responses, which in theory should result in a downloaded HTML file that was then discarded as not-a-PDF.

**Comment by dstillman** [comment]
Unless you're loading the URL in a browser that can handle a webpage that does a JS redirect, this isn't fixed. This is not the same as the other sites. It's an intermittent anti-bot protection. Sometimes it's a direct PDF download and sometimes it's not.

The S3 link above is an example URL that does a JS redirect to a PDF.

**Comment by michalrentka** [comment]
Yeah I thought the sciencedirect link in the forum post was supposed to be broken, I tested and it worked, so I didn't test your url. Now it should be actually fixed.
