### ISSUE TITLE
Share extension: Show PDF icon with X on download failure

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#398]
Instead of the (!) badge, we should have a version with a red X to better match the red X that the Zotero Connector shows. It's not really an error state — if you don't have access, failing is perfectly normal behavior and just needs to be communicated.

**Comment by michalrentka** [comment]
The red x with red attachment name looks more like an error to me than a little red circle with an "!". It's also consistent with the iOS app UI.

Anyway do you want to add some message there to communicate the issue or do I just put the x with red title there?

**Comment by dstillman** [comment]
To be clear, I was just suggesting a PDF icon with a red x badge, not a full-height X like in the Zotero Connector. Specifics of the icon aside, "x" is definitely better than "!" for this as a symbol. "!" means something went wrong. "x" just means something doesn't apply or exist.

No need for extra text. I forgot that we color the text red in the Connector. Let's try with just black text for now and see if that's clear enough.

**Comment by michalrentka** [comment]
@dstillman unfortunately the whole badge is a .png, so I'll need an updated image from @flachware (or anyone). I wanted to edit existing icons, but the dark one is transparent and I had hard time matching the color.

**Comment by dstillman** [comment]
Sorry, what do you mean by "the whole badge is a .png"? And which color are you trying to match?

**Comment by michalrentka** [comment]
@dstillman I have these now:

![attachment-detail-download-failed](https://user-images.githubusercontent.com/1022956/145356911-e314bdab-f6db-451b-8421-651c2a617be8.png)

<img width="11" alt="attachment-detail-download-failed@2x" src="https://user-images.githubusercontent.com/1022956/145356915-9f75b358-55b0-4af7-95fd-6676ad40e534.png">

![attachment-detail-download-failed@3x](https://user-images.githubusercontent.com/1022956/145356916-81c38ab0-361f-44c1-b4c3-c8157982f6e8.png)

![failed-dark](https://user-images.githubusercontent.com/1022956/145356917-f0ba356a-0669-4f76-b767-cca747e0f903.png)

<img width="11" alt="failed-dark@2x" src="https://user-images.githubusercontent.com/1022956/145356918-29463fe5-46c4-40e1-ae18-810944ac2467.png">

![failed-dark@3x](https://user-images.githubusercontent.com/1022956/145356921-ec872df8-f5b1-4610-aeec-45142e8be39e.png)

The last 3 are transparent. If we had original files it would be easier to replace.

**Comment by flachware** [comment]
@michalrentka you need these (!) badges with an (x) instead?

**Comment by michalrentka** [comment]
@flachware that's right, thanks!

**Comment by flachware** [comment]
Here you go: [attachment-detail-download-failed-icon.zip](https://github.com/zotero/zotero-ios/files/7691428/attachment-detail-download-failed-icon.zip)
