### ISSUE TITLE
Share extension: Failure state after successful save from ScienceDirect

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#399]
Testing on https://www.sciencedirect.com/science/article/pii/S0968090X21004307

The above open-access URL saves properly via the browser-based download, but then after the save completes the popup stays open, "Save to Zotero" is grayed out, and the PDF icon shows (!).

Possible the timeout is still triggering even after the save?

**Comment by michalrentka** [comment]
I can't reproduce, but I added another safety. If this continues for you send me a debug log, we'll see whether both events are firing.
