### ISSUE TITLE
`unreadableArchive` for PDF download

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#402]
https://forums.zotero.org/discussion/93442/file-attached-could-not-be-found-error-in-zotero-ios-for-shared-library

> (+0004770): HTTP GET https://api.zotero.org/groups/3822188/items/R95MAE63/file succeeded with 200
[ERROR] Zotero(+0000134): AttachmentDownloader: failed to download attachment R95MAE63, group(3822188) - unreadableArchive	

This attachment is marked as `application/pdf` and the PDF is available online.

(Not sure if this has been fixed since the last public build.)

**Comment by dstillman** [comment]
A second report in that thread

**Comment by michalrentka** [comment]
Oops. I forgot to limit webdav zip processing to my library. Since WebDAV is enabled, I'm trying to extract the PDF out of ZIP file, but this is actually downloaded from ZFS and there is no ZIP... Fixed. Users will be able to download attachments from groups when they update.
