### ISSUE TITLE
WebDAV: Invalid values for `mtime` and `md5`

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#406]
https://forums.zotero.org/discussion/comment/396265/#Comment_396265

A .prop file with invalid values (`0` and `<null>`) gets uploaded, and then the API rejects the registration request due to the invalid MD5.

Awaiting Debug ID

**Comment by michalrentka** [comment]
This is related to #400. It happened to me when switching between ZFS and WebDAV while testing #409. So apparently the fix in #400 didn't fix this completely, I'll investigate further.
