### ISSUE TITLE
Show Item button for sync errors

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#413]
For something like https://github.com/zotero/zotero-ios/issues/412, it would be nice to include a "Show Item" button in the sync error popup when we can link the error to a specific item, so that people can at least delete the item as a workaround.

General select logic in desktop app tries the current collection followed by either the library root or the trash.

**Comment by michalrentka** [comment]
It's a good idea, but when there are multiple issues across multiple libraries, I'm not sure how that would work. I guess I could just show item keys in the error message and have a button to copy those keys and the user could just copy keys and paste them in search in given library (this can be automated for single library) and there the user can do whatever.

**Comment by dstillman** [comment]
In the desktop app we only show the first error. That might change at some point, but often when there are errors they're all the same anyway, and if there's a problem it generally needs to be resolved one way or another. And it's a little silly to just show 8 copies of the same error message. So maybe just show the first error and have a button for that?

For multiple libraries, you can always trigger a sync for a specific library by pulling down within that library, right? (Or does that sync all libraries?)

**Comment by michalrentka** [comment]
Alright I'll show the first error only. Currently pulling down triggers a sync for all libraries, but it makes sense to change that too.

**Comment by michalrentka** [comment]
So I made it so that the button opens a list of items with a search of given item key. This way I could open error for multiple items as well (just separate item keys with ","). You can't delete item from item detail, so I didn't open that immediately.

![IMG_0202](https://user-images.githubusercontent.com/1022956/149338083-d2b4f22c-2a9e-4dac-a75e-d9e7bd443d81.PNG)

**Comment by dstillman** [comment]
Still getting an error without "Show Item" for a different sync error:

"Unable to upload attachment: [filename and key]. Please try removing and re-adding the attachment."

We should show the button for that one too.
