### ISSUE TITLE
Add "Empty Trash" button to trash section

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#426]
@dstillman @stakats 

When "Trash" is selected in sections screen, the navigation bar shows the same search, "+" and "Select" buttons as in other collections. 

I guess it would be more appropriate to show "Empty Trash" (which is disabled when there are no items in trash) instead of "+" and "Select"? Or maybe keep "Select" if you want to select multiple options but not trash everything?

![IMG_2742AEB2CBF4-1](https://user-images.githubusercontent.com/1022956/154450190-827861fc-6a2e-415f-9070-ea243a41f375.jpeg)

**Comment by dstillman** [comment]
I think Select is still useful (if we have a button at the bottom for deleting permanently), but we should definitely remove the +. And then we could add Empty Trash to the right of it.
