### ISSUE TITLE
Remove "About the Zotero for iOS Beta"

### ISSUE THREAD

**Issue by stakats** [zotero/zotero-ios#428]
I don't think we need this at launch and can remove now. Thoughts?

**Comment by ashutoshsaboo** [comment]
Just came across this. Woah, is the final v1 launch (for everyone) this nearby? 🚀

**Comment by michalrentka** [comment]
I'm fine with this, @dstillman do you want to change this to something else or remove completely?

**Comment by dstillman** [comment]
We can just remove. Maybe at some point we'll want a "Documentation" link above the "Support and Feedback" link, but we don't currently have anything relevant to iOS to link to.
