### ISSUE TITLE
Saving PNAS article hangs

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#451]
If I try to save https://www.pnas.org/doi/10.1073/pnas.0500232102 from iOS, it hangs on "Saving with Atypon Journals". It works on the desktop.

D547344847

**Comment by michalrentka** [comment]
@dstillman the `https://www.pnas.org/action/showCitFormats?doi=10.1073/pnas.0500232102` request fails with "too many redirects". I didn't handle the error message correctly though, so I fixed that. But this link won't work correctly anyway.

**Comment by dstillman** [comment]
Hmm, this still shouldn't fail, though.

Are we sending page cookies with translator HTTP requests?

That URL will redirect to a `cookieSet=1` URL if there's no cookie, and if setting the cookie doesn't work (e.g., in a non-browser context, which I assume is what we have on iOS) it will redirect to a `cookieAbsent` page. This means it probably fails in translation-server and various desktop-app contexts as well.

The reason it would work in the Zotero Connector is that the cookie would already be set from the original page load, so those cookies would be sent with the `showCitFormats` request. Are we able to do that?

**Comment by michalrentka** [comment]
@adomasven / @AbeJellinek I am at a point when if I return `docURL` in the proxy: https://github.com/zotero/zotero-ios/blob/d704e6ff16babe73b1e1c43bd20fe68f021fdb5c/ZShare/Assets/translation/http.js#L252-L254 I get this error from translation: https://gist.github.com/michalrentka/fa9f229ce096f754f7e025516eb29618

When I try to change it to `{ toString: () => docURL, href: docURL }` I get https://gist.github.com/michalrentka/025953dc56557166c06f6834bd4a9753. 

`{ toString: () => docURL.toString(), href: docURL }` works with PNAS, but fails on https://www.goodreads.com/book/show/1413119.The_Geopolitics_Reader (and other websites) with https://gist.github.com/michalrentka/2ccfc78c79bee7ac9a16475193e9ba87

**Comment by adomasven** [comment]
@michalrentka Look a few lines above https://github.com/zotero/zotero-ios/blob/d704e6ff16babe73b1e1c43bd20fe68f021fdb5c/ZShare/Assets/translation/http.js#L248-L249

Perhaps the `docURL` variable needs clarifying/renaming to `location` after parsing and adding `toString()`. I remember we already had this mixup some time ago. Reading through your code I don't see where `HTTP.wrapDocument()` is called when running `HTTP.processDocuments()`, which is possibly why `document.location == null` in `utilities_translate.js:219`
