### ISSUE TITLE
Cursor jumping to end of annotation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#454]
https://forums.zotero.org/discussion/94935/ios-cursor-jumping-to-end-of-annotation-d565900943

**Comment by warwickmm** [comment]
Here's another debug ID: D553769926

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/405638/#Comment_405638

**Comment by michalrentka** [comment]
Should be fully fixed this time.
