### ISSUE TITLE
WebDAV verification failure with `@` in path

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#464]
https://forums.zotero.org/discussion/95358/webdav-error-ios-1-0-1-build-1-iphone

I didn't test this, but looks like it might be getting double-encoded?

**Comment by michalrentka** [comment]
Seems like it's double encoded, but when I try it with my local webdav it doesn't encode at all and I can't reproduce this. I asked for account screenshot to see exactly what this user enters there so that I can test with that.

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/410012/#Comment_410012

Seems not fixed?

**Comment by dstillman** [comment]
Oh, I guess we're tracking in https://github.com/zotero/zotero-ios/issues/490.
