### ISSUE TITLE
Match annotations by item key in annotations sidebar

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#465]
Trying to debug https://github.com/zotero/zotero-ios/issues/460, I realized I didn't have any way of identifying a broken annotation. Can we match annotations by item key in the annotations sidebar, same as for parent items in the items list?

**Comment by michalrentka** [comment]
@dstillman not sure what you mean here. On iOS in items list we don't show children. And when I split an annotation into multiple ones, I don't store which annotations are related this way. Does backend keep track of this?

**Comment by dstillman** [comment]
This is about the annotations sidebar. I'm just saying you should be able to paste an annotation item key there to filter to just that annotation.
