### ISSUE TITLE
App URL schemes don't work

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#466]
https://forums.zotero.org/discussion/95395/ios-opening-attachments-with-custom-schemes

**Comment by dstillman** [comment]
Reported as still not working: https://forums.zotero.org/discussion/comment/404605/#Comment_404605

**Comment by michalrentka** [comment]
There is a function, which should tell me, whether iOS can open a custom url or not. It seems, the function doesn't work for custom urls and just reports that iOS can't open it. If I just open the url without checking it, it works. But if you don't have the app installed, then nothing happens after you tap that link. I have no way of checking whether something opened or not.

So I just removed the check and try to open it immediately. In the worst case, nothing will happen (users won't see any error message).
