### ISSUE TITLE
AttachmentDownloader: failed to download attachment

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#469]
https://forums.zotero.org/discussion/95421/ios-cant-download-pdf-via-webdav
https://forums.zotero.org/discussion/95505/ios-cant-download-files-via-webdav

> AttachmentDownloader: failed to download attachment R74LVARH, custom(Zotero.RCustomLibraryType.myLibrary) - cancelled

**Comment by michalrentka** [comment]
In logs they both only showed that they cancelled the download. I asked for more info.

**Comment by michalrentka** [comment]
This should be fixed by 4b3d805954ec8f5bdd12ccf439b751102116b4ba
