### ISSUE TITLE
Clear button not showing up in settings

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#470]
https://forums.zotero.org/discussion/95557/ios-close-button-disappears-at-settings-dialog

**Comment by michalrentka** [comment]
This seems to be a SwiftUI bug which is fixed in iOS 15. I can rewrite settings screen in UIKit, but I guess this is a minor issue. You can still tap the background to dismiss.

**Comment by michalrentka** [comment]
@dstillman do you want me to rewrite this in UIKit or just ignore this issue? If their device supports iOS 14, it will support iOS 15 as well, so they can just update their device. But I understand if someone doesn't want to. It's not hard to re-write, just maybe unnecessary.

**Comment by dstillman** [comment]
Ignore.
