### ISSUE TITLE
Include Zotero version in user agent

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#477]
User agent includes only "Zotero/1" rather than the full version + build.

**Comment by michalrentka** [comment]
I believe that `1` is actually a full version. The first release was just `1`. But I'm manually including default Alamofire user agent now which looks like this for me: `Zotero/1.0.2 (org.zotero.ios.Zotero; build:2; iOS 15.4.1) Alamofire/5.5.0`. I also filled some places which could have missed that. Hopefully we'll have more info for all requests now.
