### ISSUE TITLE
Swiping up from bottom to trigger app switcher changes page in PDF reader

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#478]
https://forums.zotero.org/discussion/95889/bottom-pages-list-on-ipad-makes-changing-apps-problematic

**Comment by michalrentka** [comment]
This seems to be a PSPDFKit issue. I "fixed" this by changing the type of visible scrubber view, which seems to ignore the bottom edge drag gesture. I reported this to PSPDFKit and will switch back to previous appearance when this bug is fixed.

**Comment by michalrentka** [comment]
Looks like this is a bit harder from PSPDFKit side, not exactly sure why, but their recommendation is to just use another type of scrubber bar (which I already did). They are not planning to change this in near future, so I'll close this ticket. Maybe this will change at some point and we'll be able to use other alternatives.
