### ISSUE TITLE
Filter annotations in sidebar by tag and color

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#491]
Similar to desktop

**Comment by michalrentka** [comment]
@dstillman here's a preview of what I've done:
![IMG_0245](https://user-images.githubusercontent.com/1022956/172174814-45412344-23c3-49d7-931c-b15f2aac2778.PNG)
![IMG_0246](https://user-images.githubusercontent.com/1022956/172174867-2c8061db-99fe-4244-b4f7-de62c5455112.PNG)

Any idea for a better string when no tags are picked?
