### ISSUE TITLE
Restore state after restart

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#492]
https://forums.zotero.org/discussion/96709/saving-state-on-ios

At least selected collection and any open PDF. Scroll position isn't necessary.

**Comment by michalrentka** [comment]
So there is/was a little UIKit issue when trying to show the PDF reader after app launch. I was able to work around it in a manageable way:

https://user-images.githubusercontent.com/1022956/167841409-32686dba-29d6-492a-8b02-40202066549e.mov

There is still a little flash, but I think that's fine. For comparison, it looks like this with default UIKit animations:

https://user-images.githubusercontent.com/1022956/167841630-535b5e91-caa9-48cc-8ad9-ebbbe7095c54.mov

**Comment by dstillman** [comment]
Are those screenshots reversed?

**Comment by dstillman** [comment]
(Unless I'm misunderstanding the issue. The one that switches back to the library seems worse than the text briefly disappearing. Or is there some other problem with the first one?)

**Comment by dstillman** [comment]
Oh, never mind, I misread. First one is the fixed one.
