### ISSUE TITLE
Show emoji colored tags directly in items list

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#496]
https://forums.zotero.org/discussion/97002/color-assigned-tags-in-ios-not-updating-properly

Similar to desktop. Not totally sure how we want to display these, since we're overlapping colored tags on iOS.

See https://github.com/zotero/zotero/commit/f9035c8fda715add49c2b185ef7e240e7e045ec3 for the desktop implementation (regexp, removing emoji and ZWJ and checking for remainder…).

**Comment by michalrentka** [comment]
I don't see emojis in the items list on desktop version. Also as you mentioned, I'm not sure how to display them since we're overlapping colors there. Overlapped emojis would probably be useless.

**Comment by michalrentka** [comment]
@dstillman any ideas? Maybe I can just show emojis as a whole with some spacing between them and then remaining color tags would just stay the same?

**Comment by michalrentka** [comment]
Related to #797, but that one is improved. Closing as duplicate.
