### ISSUE TITLE
Old tags still show up in tags list?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#497]
https://forums.zotero.org/discussion/97002/color-assigned-tags-in-ios-not-updating-properly

I haven't tried to reproduce this.

**Comment by michalrentka** [comment]
> The old color-assigned tags aren't "forgotten" on iOS after changing them, i.e. when I try to assign tags to items in the iOS version I first see the old version with the letters + punctuation at the top of the tag list. The tags with the emojis are at the bottom of the tag list. Moreover, while the tags at the top of the list still reflect their assignment 1-9, their replacement emoji tags are not in the corrector order, which leads me to believe the color-assigned tags in aren't being correctly reassigned in the iOS version.

I don't understand the issue at all. You add an emoji tag, it appears on bottom (emojis are sorted that way on iOS, I can change that so that they appear on top). Tags are sorted alphabetically currently, so not sure what the "assignment 1-9" means or what should happen with colored tags when an emoji is added.

**Comment by dstillman** [comment]
More old tags still showing up:

https://forums.zotero.org/discussion/96204/zotero-on-ios-deleting-tags-from-library-tag-list

I've confirmed that these tags are no longer associated with any items.

**Comment by dstillman** [comment]
The first report is about assigning an emoji to an existing colored tag. They seem to be saying they're renaming an existing colored tag to an emoji, which should cause it to show the emoji in the same position at the top of the tag selector (in positions 1 through 9, as assigned on the desktop app), but instead the old tag is still showing in the original location and the emoji is showing up as a regular tag sorted (currently) at the bottom. (Yes, would be good to sort those at the top, before alphanumeric non-colored tags.)

I assume it's some sort of discrepancy between the tagColors setting vs. the tag associated with the items?

**Comment by dstillman** [comment]
Actually seems possible that these were renamed tags, so maybe related issues?
