### ISSUE TITLE
PDF reader: Eraser tool for ink annotations

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#499]
https://forums.zotero.org/discussion/96753/an-eraser-tool-needs-to-be-added-to-the-zotero-ios and others

(Needs an icon)

**Comment by ZJsheep** [comment]
I am also interested.

**Comment by michalrentka** [comment]
I forgot about this ticket, implemented in dcf4805969872d3fd64b38628a8e5044ebe1a011.
