### ISSUE TITLE
Incorrect/inconsistent attachment opening with multiple attachments

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#504]
https://forums.zotero.org/discussion/97487/inconsistent-attachments-being-opened-by-default-across-devices

This item has four PDFs.

This is how the correct attachment should be chosen:

```
 * Looks for attachment in the following order: oldest PDF attachment matching parent URL,
 * oldest PDF attachment not matching parent URL, oldest non-PDF attachment matching parent URL,
 * old non-PDF attachment not matching parent URL
```
"oldest" here means the attachment's `dateAdded` field.

**Comment by warwickmm** [comment]
The desktop app correctly opens attachment ZC3PYUGJ.

On the iPad, attachment Q88MKHPL is opened.

On the iPhone, attachment UIBA459E is opened.

**Comment by michalrentka** [comment]
@warwickmm how are you opening the attachment? Do you open it by tapping the item in item list or do you go to item detail (tapping the "(i)" icon in item list) and there you tap "View PDF"?

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/comment/409887/#Comment_409887
