### ISSUE TITLE
WebDAV fileMissingAfterUpload error

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#512]
https://forums.zotero.org/discussion/98005/webdav-sync-4shared-not-working-in-zotero-ipad

```
(+0001685): AttachmentDownloader: download remote file 7VPP97JI

(+0000012): AttachmentDownloader: enqueue 7VPP97JI

(+0000000): AttachmentDownloadOperation: start downloading 7VPP97JI

(+0000000): WebDavController: checkServer

(+0000010): HTTP OPTIONS https://webdav.4shared.com/zotero/

[…]

(+0000004): HTTP PUT https://webdav.4shared.com/zotero/zotero-test-file.prop

(+0000000): Data: 1 bytes

(+0000000): {
  "User-Agent" : "Zotero\/1.0.3 (org.zotero.ios.Zotero; build:5; iOS 15.4.1) Alamofire\/5.6.1"
}

(+0000283): HTTP PUT https://webdav.4shared.com/zotero/zotero-test-file.prop succeeded with 200

(+0000000): {
  "Transfer-Encoding" : "Identity",
  "Server" : "520206",
  "Date" : "Thu, 23 Jun 2022 17:56:34 GMT"
}

(+0000003): HTTP GET https://webdav.4shared.com/zotero/zotero-test-file.prop

(+0000000): {
  "User-Agent" : "Zotero\/1.0.3 (org.zotero.ios.Zotero; build:5; iOS 15.4.1) Alamofire\/5.6.1"
}

(+0000178): HTTP GET https://webdav.4shared.com/zotero/zotero-test-file.prop succeeded with 404

(+0000000): {
  "Date" : "Thu, 23 Jun 2022 17:56:34 GMT",
  "Content-Type" : "text\/html;charset=UTF-8",
  "Transfer-Encoding" : "Identity",
  "Server" : "520206"
}
[ERROR] Zotero(+0000001): WebDavController: checkServer failed - fileMissingAfterUpload

(+0000002): AttachmentDownloadOperation: finished downloading 7VPP97JI
[ERROR] Zotero(+0000001): AttachmentDownloader: failed to download attachment 7VPP97JI, custom(Zotero.RCustomLibraryType.myLibrary) - fileMissingAfterUpload	
```
The logging is a little confusing here, but it looks like this isn't actually related to the 7VPP97JI file and that's just kicking off a Verify Server, right? And then an uploaded file returns a 404 immediately after the upload, which is a `fileMissingAfterUpload` error from the verify-server attempt?

Is that a fatal error for you? In the desktop app, this condition triggers a prompt:

> A potential problem was found with your WebDAV server.
> 
> An uploaded file was not immediately available for download. There may be a short delay between when you upload files and when they become available, particularly if you are using a cloud storage service.
> 
> If Zotero file syncing appears to work normally, you can ignore this message. If you have trouble, please post to the Zotero Forums.

I believe this shouldn't happen anymore for anything backed by S3, since S3 has had read-after-write consistency for a couple years, but providers backed by other file stores might still behave this way. So this probably shouldn't be a fatal error. But it's not unprecedented for file uploading to just be broken, so it's good to warn the user.

**Comment by michalrentka** [comment]
@dstillman yeah this is just a fatal error currently. I'll change it to show the message.
