### ISSUE TITLE
iOS 14.4 Support & Zotero 1.0.4 PDF Reader

### ISSUE THREAD

**Issue by hykilpikonna** [zotero/zotero-ios#519]
Hi, I'm stuck using iOS 14.4, but the Zotero app on the App Store only supports iOS 14.7 and up.

I tried modifying the Info.plist to increase the MinimumOSVersion of an existing 1.0.3 build, but it would crash on launch.

I also tried manually compiling the latest zotero-ios from the Github repo, it builds and installs successfully with my personal developer account, but the PDF viewer wouldn't open when I click it, probably due to missing token?

It would be great if you can change the minimum OS version requirement to 14.0 in the next release, it probably won't break anything.

**Comment by michalrentka** [comment]
@hykilpikonna if you want to build the app yourself and use the PDF reader, you have to get a license key from PSPDFKit. As a temporary solution you can use their free trial. We're not planning to lower the minimum OS version though.
