### ISSUE TITLE
Update schema.json to version 17

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#523]
Contains CSL 1.0.2 changes and a mapping fix that might fix a [save failure](https://forums.zotero.org/discussion/97682/error-when-saving-for-some-acm-dl-publications) (though I haven't tested in the iOS app)

**Comment by dstillman** [comment]
(This is assuming we're currently pulling/updating schema.json directly. If we're getting from one of the other submodules, we can update the submodule if necessary. Related: https://github.com/zotero/zotero-connectors/issues/390)

**Comment by michalrentka** [comment]
@dstillman I fetch schema.json from https://api.zotero.org/schema, but it seems to be on version 15

**Comment by dstillman** [comment]
Sorry, updated now.
