### ISSUE TITLE
Option to export PDF without annotations

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#526]
https://forums.zotero.org/discussion/98739/ios-share-attachments-without-embedding-annotations

Can we show a popup list when clicking the share button in the PDF reader with "Include Annotations" and "Don't Include Annotations" options, and then trigger the share sheet from there?

**Comment by michalrentka** [comment]
I implemented a simple popup, we can add more settings as we need later.

![IMG_0254423C29CE-1](https://user-images.githubusercontent.com/1022956/189657542-e764ca9f-7caf-451b-87d4-efa173dc9dca.jpeg)

**Comment by dstillman** [comment]
This is limited to Zotero annotations, right? If you're viewing a PDF with embedded annotations, I assume those will remain? So probably this should say "Include Zotero annotations".
