### ISSUE TITLE
Download failure for open-access PDF from Sage and T&F due to intermediate 503 from Cloudflare

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#530]
https://forums.zotero.org/discussion/98760/zotero-for-ios-not-downloading-attaching-pdf-to-record

https://journals.sagepub.com/doi/full/10.1177/25148486211069884
https://www.tandfonline.com/doi/full/10.1080/13569783.2021.1888708

D1875984814
D2139334164

In both of these cases, there's an intermediate Cloudflare page that returns a 503, which then does a JS (I assume) redirect to the PDF URL.

Not sure why this doesn't seem to be happening on desktop. I didn't study the requests, but are we sending the same cookies (including HttpOnly cookies) that the browser sends? I know from @adomasven that we do download fewer PDFs in desktop Safari because Safari App Extensions only have access to document.cookie and not HttpOnly cookies.

**Comment by michalrentka** [comment]
I didn't pass cookies to download requests, after doing so those 2 links work.
