### ISSUE TITLE
Add by Identifier form gets shifted to middle of screen on iPhone after pressing Lookup

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#532]
https://forums.zotero.org/discussion/98798/adding-by-identifier-seems-to-be-stuck-ios-beta

The video shows the dialog text move down to a weird position in the middle of the screen, half cut off by the keyboard.

**Comment by dstillman** [comment]
Sorry, that's an old beta. Not sure if it's current behavior.

**Comment by michalrentka** [comment]
This has been fixed in latest betas, I just checked and it looks fine on my phone, so hopefully when they update it'll work fine
