### ISSUE TITLE
Disable page flip animation if Reduce Motion is enabled

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#543]
https://forums.zotero.org/discussion/99928/disable-ios-page-flip-animation

I didn't test whether we (or PSPDFKit) are already doing this, but we should if possible.

**Comment by michalrentka** [comment]
@dstillman the pdf reader doesn't have a page flip animation. It just scrolls. Do we want to disable all animations?

**Comment by dstillman** [comment]
Sorry, I should've tested. This already exists with a single tab on the page edge.

**Comment by dstillman** [comment]
* In horizontal mode
