### ISSUE TITLE
WebDAV file download error due to file already existing

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#545]
> The file “[…].PDF” couldn’t be saved in the folder “I6DQS73M” because a file with the same name already exists."

https://forums.zotero.org/discussion/100068/cant-open-some-pdfs-in-ios-app

Can ask them to try in the beta if we think this is already fixed

**Comment by michalrentka** [comment]
@dstillman yes this should be fixed.

**Comment by dstillman** [comment]
> In Testflight 1.0.4 the same file(s) are equally not downloadable, but the error message changed to "Unable to unzip snapshot".
