### ISSUE TITLE
Startup error: `Controllers: can't create UserControllers - Error Domain=io.realm Code=1 "No such table exists`

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#552]
https://forums.zotero.org/discussion/100273/debug-id-d1553280790

**Comment by michalrentka** [comment]
We didn't have an option to export DB in this case and the user had to re-install the app to use it. I added the export option so that I can report this issue to Realm when it happens again, but this user can't reproduce anymore.
