### ISSUE TITLE
PDF reader: Zoom state not preserved on restart

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#585]
https://forums.zotero.org/discussion/101316/ios-beta-bug-ui-regression-pdf-viewer-loses-zoom-state-testflight-v-1-0-8-build-2

1) Zoom in on a page section
2) Force-quit app
3) Reopen

Zoom state is reset to full page

**Comment by jgrisham** [comment]
_Possibly related:_ [iOS: Switching light/dark appearance changes page position](https://forums.zotero.org/discussion/100939/ios-switching-light-dark-appearance-changes-page-position#latest)

**Comment by michalrentka** [comment]
This is a bug from PSPDFKit, who I'm notifying. As @jgrisham mentioned, it's related to appearance change, which is also set when you reopen the app.

**Comment by michalrentka** [comment]
Fixed by PSDPFKit in their latest release c3893a6
