### ISSUE TITLE
Excessive `lastPageIndex` uploading

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#594]
https://forums.zotero.org/discussion/comment/424423/#Comment_424423

There might be other things going on here contributing to high battery drain, but it does look like there's repeated uploading of `lastPageIndex` for the same PDF and page, every 5–15 seconds. I'm not able to reproduce this on an iPhone, just zooming and scrolling around a single page, but I can't test on an iPad at the moment.

**Comment by michalrentka** [comment]
I noticed a little bug which synced wrong page (one ahead instead of the current one) which also caused some unnecessary syncs. Also if you have continuous page transition, you can pan between pages on the edge and cause some syncs that way. So I added extra 3s debounce for page syncs.
