### ISSUE TITLE
YouTube translator fails

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#596]
https://forums.zotero.org/discussion/comment/424790/#Comment_424790

I get a webpage item from both the YouTube app and from the browser:

```
 ZShare(+0000000): State: translating with Saving with YouTube
 ZShare(+0000001): JSLOG: (4)(+0000000): Translate: Parsing code for YouTube (d3b1d34c-f8a1-43bb-9dd6-27aa6403b217, 2021-08-25 19:44:19)
 ZShare(+0000000): JSLOG: (3)(+0000001): Translate: Beginning translation with YouTube
 ZShare(+0000000): JSLOG: (3)(+0000001): Error: No title specified for item
```

**Comment by michalrentka** [comment]
@dstillman can you send me video links which didn't work for you? I tried 2 videos on web and iOS app and all of them returned video items for me.

**Comment by dstillman** [comment]
Pretty sure it's any video for me. Just reproduced with https://m.youtube.com/watch?v=_BvB0182xag&feature=youtu.be in browser. This is with 1.0.9-2 on iPhone.

**Comment by dstillman** [comment]
Oh, but maybe it's just a translator problem on m.youtube.com. This works on my iPad, where it uses www.youtube.com. So this probably isn't an iOS issue. Will reopen if it is.

**Comment by michalrentka** [comment]
Yeah I remember now that we dealt with this before. It was an issue with the mobile version.
