### ISSUE TITLE
Constant PDF reader crashes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#601]
https://forums.zotero.org/discussion/102223/over-5-crashes-in-the-last-hour

**Comment by michalrentka** [comment]
2 types of crashes:
- `NSMallocException` where the client runs out of memory when (de)serialising json, probably related to big ink annotations
- `DetailCoordinator` tries to use released `navigationController`, which is `unowned`, resulting in a crash. Possible memory leak, multitasking issue or similar.
