### ISSUE TITLE
Fit one more button on annotation toolbar on iPhone mini?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#607]
![IMG_371957975CE5-1](https://user-images.githubusercontent.com/783082/215058258-27adff0e-5edf-4037-8188-bdab4e8e3000.jpeg)

It looks like we could fit in one more button, and then with the current tools just "Eraser" would be in the menu. Possible?

**Comment by michalrentka** [comment]
@dstillman there's not enough space. I'm keeping empty space for the options (color picker) button which needs to show up when something is selected:
![Simulator Screen Shot - iPhone 13 mini - 2023-01-27 at 11 30 14](https://user-images.githubusercontent.com/1022956/215065584-976eba4c-0535-49e2-a479-eecef46096b6.png)

**Comment by dstillman** [comment]
Ah, missed that.
