### ISSUE TITLE
PSPDFKit preview rendering std::bad_alloc

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#610]
Report ID 587958935

From App Store review. No other info.

**Comment by michalrentka** [comment]
@dstillman the app crashes when PSPDFKit tries to create a preview image for some annotation. I can send this to PSPDFKit, but ideally I'd send a PDF file with it. Can you ask the user for the PDF?

**Comment by dstillman** [comment]
I can respond to the review, but they almost certainly won’t get us the file. (Review is in Chinese.)

**Comment by michalrentka** [comment]
Ok I'll send it to PSPDFKit, maybe they'll notice something just from the crash report.

**Comment by michalrentka** [comment]
Related: https://forums.zotero.org/discussion/102811/and-another-crash-of-the-ios-app
