### ISSUE TITLE
Edited field values are lost when switching away from app

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#611]
1) Switch into edit mode on an item
2) Type something in a couple fields
3) Switch away from the app (even to home screen)
4) Switch back

The edited fields are cleared.

**Comment by michalrentka** [comment]
@dstillman I'm not able to reproduce this. I tried editing existing item or creating a new empty one, but everything was in place when I returned to the app.

**Comment by dstillman** [comment]
This was on my phone, for what that's worth.

**Comment by dstillman** [comment]
Yeah, I can't reproduce on iPad (though if I tap in an empty field before leaving the cursor does bizarrely jump to a different field two fields up from the one I was in).

**Comment by michalrentka** [comment]
Thanks, I was able to reproduce on phone.
