### ISSUE TITLE
Question - port the iOS version to the Mac

### ISSUE THREAD

**Issue by mugsuk** [zotero/zotero-ios#614]
Is the iOS version being ported to a macOS version?

Thanks for the excellent software buy the way.

Yours sincerely

Murray

**Comment by dstillman** [comment]
No, we offer a dedicated Mac app with much more functionality and have no plans to make the iOS app available on macOS.

Please post all questions to the Zotero Forums. We don't use GitHub for end-user support.

https://github.com/zotero/zotero-ios/blob/master/CONTRIBUTING.md
