### ISSUE TITLE
UIKit crash: Apple Pencil text view editing "NSTextContentStorage: Inconsistent element cache state"

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#629]
https://forums.zotero.org/discussion/103394/report-id-1091941411

**Comment by dstillman** [comment]
Same?

https://forums.zotero.org/discussion/103705/crash-log-and-report-id

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/103931/crash-report

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/104279/crash-report

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/105234/bug-ios-app-on-ipad-crashes-when-while-annotating-with-apple-pencil
