### ISSUE TITLE
DetailCoordinator topViewController swift_abortRetainUnowned

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#630]
https://forums.zotero.org/discussion/103409/report-id-231474425
https://forums.zotero.org/discussion/103695/crashes-on-pdf-on-ipad-when-reading-docs-error-log-237642545

**Comment by michalrentka** [comment]
Also reported in #601

**Comment by dstillman** [comment]
https://forums.zotero.org/discussion/103917/zotero-is-crashing-when-the-icon-on-the-right-side-of-a-paper-is-clicked
