### ISSUE TITLE
Opening certain non-standard size PDFs crashes app

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#641]
https://forums.zotero.org/discussion/103754/opening-certain-non-standard-size-pdfs-crashes-the-ios-app-workaround-found

PDF sent via email. (I didn't try to reproduce.)

**Comment by dstillman** [comment]
(Or maybe not. Second PDF sent that doesn't reproduce.)

**Comment by michalrentka** [comment]
Fixed with most recent PSPDFKit update
