### ISSUE TITLE
Tag entry view appears behind standalone note

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#645]
https://forums.zotero.org/discussion/103287/ios-and-ipados-tag-selector-wont-open

If you tap the bottom Tags bar in a standalone note, nothing appears, but then when you close the note the tag interface is there in place of the items list. If you tap the bar multiple times, you have to close multiple views.

**Comment by michalrentka** [comment]
This is fixed by refactorings in #71, but I can separate it if we want to push a quick fix for this first.

**Comment by dstillman** [comment]
No, that's OK.
