### ISSUE TITLE
"Save Files" pref not followed for Add by Identifier

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#660]
1) Disable "Save Files"
2) Enter `arXiv:2004.13001` in Add by Identifier.

A file will be added.

**Comment by angiemugo** [comment]
@dstillman , I noticed that when an attachment download is in progress and you close the pop up window, the download cancels. Is this the intended behavior?

**Comment by dstillman** [comment]
Close how? With "Cancel" or with "Close"? Do we display Close before the download is done? (The PDF for the above identifier downloads too quickly for me to tell.)

**Comment by angiemugo** [comment]
![IMG_1847D77E27CF-1](https://user-images.githubusercontent.com/23118371/235891839-536de74b-c679-47d4-9b2b-7434c722052f.jpeg)

when you hit close here.

**Comment by dstillman** [comment]
That shouldn't cancel the download, no. (Also we should fix that being cut off.)

**Comment by angiemugo** [comment]
> That shouldn't cancel the download, no. (Also we should fix that being cut off.)

will fix that! 
Yeah, I'd seen this. What happens is when the table view's height is larger the table view is made scrollable. The solution I had was to scroll the table view to the bottom. What do you think? cc @michalrentka

**Comment by michalrentka** [comment]
@angiemugo there can be multiple attachments, so simply scrolling without resizing won't help. I think there's already an attempt to resize the window to proper height based on contents, but something seems to be calculated incorrectly or the calculation is fine but made when the layout is not finished yet. I think this window is `ManualLookupViewController`, there should be something related to `preferredContentSize`, so I'd start there.

**Comment by angiemugo** [comment]
I am going to create a separate issue for the download being canceled when the view is dismissed so that I work on it separately.
