### ISSUE TITLE
Annotation previews are not re-rendered when you switch between light/dark mode

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#669]
Reproduction steps: 
1. open some PDF with annotations, open sidebar, previews are rendered
2. change between light/dark modes
3. annotations are not re-rendered

**Comment by michalrentka** [comment]
@angiemugo actually, I re-tested again. It works when you switch color mode the first time, but when you switch back, it's stuck again:

https://user-images.githubusercontent.com/1022956/234802233-d0fdf579-1394-4225-a60d-62e6ca4903b9.MP4

**Comment by angiemugo** [comment]
@michalrentka , I noticed these are re-rendered only after scrolling. I will change that behavior and reload every time the interface style is changed

**Comment by michalrentka** [comment]
It re-renders once even without scrolling, so something is right :). Just have to figure out why it doesn't re-render on consecutive interface changes.

**Comment by angiemugo** [comment]
You're right! Okay. On it! :)
