### ISSUE TITLE
Add by identifier popup UI cut off

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#689]
When adding items by identifier (in items list tap "+" -> "Add by Identifier" and add one or more identifiers, for example find some papres on arxiv.org and paste their identifiers), the UI can be a bit cut off. It should grow vertically as much as possible and when there's no more vertical space it should be scrollable.

![235891839-536de74b-c679-47d4-9b2b-7434c722052f](https://github.com/zotero/zotero-ios/assets/1022956/d44f1799-c15a-465b-a772-a3252d5c0ca2)

**Comment by mvasilak** [comment]
Problem only appears when there is one lookup item, that has an attachment to download.

There are also some issues when multiple lookup items are downloaded:
- When the internal table view updates there are flashes of cells overlapping. Final update is always ok.
- In iPhone, the table view doesn't expand beyond the previous keyboard top, even though the keyboard has disappeared.

I guess that these problems are not that crucial, as probably most users don't add that many identifiers at the same time. If there are related user complaints in the future, I would suggest to refactor the existing implementation, e.g. by moving to a collection view based solution, to simplify the UI hierarchy.
