### ISSUE TITLE
Scribble crash

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#719]
https://forums.zotero.org/discussion/106056/error-report-report-id-is-2033633306

I guess not entirely fixed.

**Comment by michalrentka** [comment]
@mvasilak if I remember correctly you fixed this initially? Can you take a look at this again?

**Comment by mvasilak** [comment]
It's a different text view, with the same issue. Unless there is reason not to, I suggest we subclass `UITextView`, to force the use of TextKit 1 in one place, and use this throughout the app.

**Comment by michalrentka** [comment]
Let's do that
