### ISSUE TITLE
Repeated full syncs

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#724]
https://forums.zotero.org/discussion/106154/pdf-not-synchronizing-after-adding-it-in-ios-zotero-app

Search for TFDGD5LG

**Comment by michalrentka** [comment]
@dstillman it could be fixed with https://github.com/zotero/zotero-ios/pull/696. I thought it was included in 1.0.17, but it doesn't seem to be.

**Comment by dstillman** [comment]
They fixed it another way, so we'll have to see if others report anything like this.
