### ISSUE TITLE
Image annotation share size is incorrect

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#725]
I picked "Large (480 KB)" for an image annotation, AirDropped it to my Mac, and the resulting JPEG is 907 KB.

**Comment by mvasilak** [comment]
I tried to reproduce it in an iPad Air, and I find that
- If I save the image to Photos, the size is correct, and then if I AirDrop from Photos to a Mac, size is also the same.
- if I AirDrop directly to a Mac, size is indeed larger, almost double, but resolution is the same.

In the implementation, I wrote:
> By default UIActivityViewController shares a JPEG image with 0.8 compression quality,
> so we compute the image size as such. Actual image produced can be overriden if we need to.

It may be related, as some share options could use the UIImage instance differently. 
I'll investigate if we need to explicitly override image creation.
