### ISSUE TITLE
Lookup table view animation glitch

### ISSUE THREAD

**Issue by mvasilak** [zotero/zotero-ios#734]
When downloads are in progress, the table view reloads for progress updates are creating this weird blinking:
https://github.com/zotero/zotero-ios/assets/1022956/3d88f21f-54d9-4ee3-a8cf-dbc85412c01f

**Comment by michalrentka** [comment]
I don't see this happening anymore. @mvasilak can you still reproduce?

**Comment by mvasilak** [comment]
@michalrentka I cannot reporduce anymore. I'll close the issue, and we can re-open if needed.
