### ISSUE TITLE
Attachment is deleted if Create Parent Item screen is canceled

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#778]
https://forums.zotero.org/discussion/comment/445381/#Comment_445381

**Comment by dstillman** [comment]
Details on the ticket, but basically the parent item is being created as soon as the screen is opened, and then if you don't tap Cancel fast enough, that syncs, and then Cancel deletes the item, which also deletes the attachment. Bad!

**Comment by michalrentka** [comment]
@dstillman we changed this before to match the desktop behavior, which does the same thing (except there's no "Cancel" to delete the attachment, which is a bug of course). So do I actually not create the item before tapping "Save" or can I create it and then delete just the parent in case of "Cancel"?

**Comment by dstillman** [comment]
I don't see why this would've been about the desktop behavior, which doesn't have a screen like this — that's not really comparable. But maybe it was about notes and attachments being editable without queuing everything behind a Save, which seems like it would be complicated and dangerous.

Can we 1) not create a parent item until there's actually a reason (note, other attachment, or Save) and 2) change Cancel/Save to Done if a parent item has been created?

**Comment by michalrentka** [comment]
> I don't see why this would've been about the desktop behavior, which doesn't have a screen like this — that's not really comparable. But maybe it was about notes and attachments being editable without queuing everything behind a Save, which seems like it would be complicated and dangerous.
> 
> Can we 1) not create a parent item until there's actually a reason (note, other attachment, or Save) and 2) change Cancel/Save to Done if a parent item has been created?

When would the 2) occur? When you long press to create parent for some standalone attachment and then for example you add a note, then the parent item is created in background and only "Done" would show up? Can't we just show "normal" non-editing screen when the parent item is actually saved? So instead of "Done" you'd see "Edit" and "View PDF" on right side and "Back" on left side as usually.

**Comment by dstillman** [comment]
Yes, (2) would happen if you created a note or added another attachment.

But yeah, we can show normal editing screen at that point.

**Comment by michalrentka** [comment]
@dstillman after a bit thinking there are still some discrepancies.

1) If you open an item detail, you start editing, you add a note, you're still on editing screen with "Save" and "Cancel" which may feel a bit like you still need to tap "Save" to actually save the note. We mentioned above that we could just disable the editing mode, but that might be annoying in some cases. I think it would be interesting to just hide notes, attachments and tags in editing mode and keep editing mode to editing metadata. You can edit notes, attachments and tags outside of (metadata) editing mode.

2) 1 sounds good enough, but what if user edited multiple fields and/or is typing a bigger abstract and suddenly the device shuts off or it slips in hands and you tap "Cancel" accidentally. Do we even need Save/Cancel? Can't there just be "Done" and stuff would just immediately save to database and sync?

**Comment by dstillman** [comment]
So for normal usage, there's still an Edit button in the toolbar, but it takes you into metadata-editing mode without the things at the bottom?

And though we have a separate edit mode with open fields — because we don't want to make the normal display mode large enough to have reasonable tap targets — we do we the same kind of auto-save on blur that we do on desktop?

And then for this, we open in edit mode, and when you tap Done you're back at the details pane and can add the other things?

That means there's no way to cancel this if you trigger it accidentally, which isn't ideal. Would it be too weird to show Cancel (and not Done) before you edit any fields, and then show Done as soon as you do?

**Comment by michalrentka** [comment]
> So for normal usage, there's still an Edit button in the toolbar, but it takes you into metadata-editing mode without the things at the bottom?

Yes

> And though we have a separate edit mode with open fields — because we don't want to make the normal display mode large enough to have reasonable tap targets — we do we the same kind of auto-save on blur that we do on desktop?

Yes, either save on blur or while typing with some debounce.

> And then for this, we open in edit mode, and when you tap Done you're back at the details pane and can add the other things?
> 
> That means there's no way to cancel this if you trigger it accidentally, which isn't ideal. Would it be too weird to show Cancel (and not Done) before you edit any fields, and then show Done as soon as you do?

Hmm, I guess in case of "Create parent item" and "Duplicate item" it would make sense to show the editing screen with Save/Cancel and after you save initially it would work as mentioned above. 
Or we'd show Done/Cancel, so the item would be automatically created (as it is now on iOS and desktop) and on Cancel it would be just deleted (I'd fix the bug where attachment is deleted with parent item), otherwise it would work as mentioned above. If you don't like that it would sync in the meanwhile, we can just mark the database item to not sync until it's saved initially.

**Comment by dstillman** [comment]
Actually, probably should hold off on syncing the item generally while the edit pane is open, even if we're saving the data as you go. No reason for the extra sync churn. (We do sync on desktop, debounced, but, I dunno, this might be slower.) But still should update the pane if remote sync changes come in.

**Comment by michalrentka** [comment]
One last thing I can think of is what if the user leaves this item and kills the app or the app crashes. Do I leave the item marked as no sync until user re-opens and saves again? Or do I just mark all of these items as syncable on app launch? I'd go with sync on app launch.

**Comment by dstillman** [comment]
If you can't just somehow pause syncing for the item as long as the pane is open, then yes, syncable on app launch.
