### ISSUE TITLE
transplant to android

### ISSUE THREAD

**Issue by analytic-bias** [zotero/zotero-ios#793]
> Zotero does not use GitHub Issues for bug reports or feature requests.

This is not a bug report or a feature request.

----

Today I found out about this project https://mutata.io on the web and was wondering if there's a possibility of running this app on my android phone as it seems this app is more polished than the non-actively maintained ones listed [here](https://www.zotero.org/support/mobile).

I've already emailed them to see if they have any procedures with FOSS projects to preserve AGPL compliance as well as the spirit of FOSS in the zotero community.

Any thoughts?

**Comment by dstillman** [comment]
An Android app is under development. Please post further questions to the Zotero Forums.

**Comment by analytic-bias** [comment]
> An Android app is under development. Please post further questions to the Zotero Forums.

Great news! Done (https://forums.zotero.org/discussion/108924/zotero-ios-transplant-to-android#latest), thanks!
