### ISSUE TITLE
Changes to emoji tags

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#797]
- Emoji tags should show up in items list - they should show up first, then overlapped colored circles.
- If tag contains text and emojis, strip text and pick first emoji group and show that in item list. Show whole tag in other places.
- Emoji tags don't have to be colored to show up as emojis
- Tags in tag picker should sort in this order: colored, emojis, other.

https://github.com/zotero/zotero/pull/3330/files#diff-6d32b0ceca7a10685e44094f16b83bb7f59b8db13ee9b3b388cd7ad24b7f10f5R226-R241
https://github.com/zotero/zotero/issues/3324#issuecomment-1679683989

**Comment by asan-emirsaleh** [comment]
It is very useful option. Waiting for it to be included to Zotero beta release.

**Comment by michalrentka** [comment]
@asan-emirsaleh it's already in beta, so you can check it out.
