### ISSUE TITLE
Hang on unexpected error during WebDAV verification

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#845]
https://forums.zotero.org/discussion/111761/ios-webdav-sync-problem

> HTTP PUT https://[…]/zotero/zotero-test-file.prop failed with 507

But any unexpected error code should throw an error. Unknown ones show an unknown-error message. Desktop would show:

```
An unknown error occurred.

Please check your file sync settings or contact your WebDAV server administrator.

HTTP 507
```

https://github.com/zotero/zotero/blob/872e7b24278a2f00d7558aa9055d7f641c1a768a/chrome/content/zotero/xpcom/storage/webdav.js#L778-L807

**Comment by mvasilak** [comment]
I think in this case the workflow is stuck and it never fails, for an error to be displayed, according to the user's comments and debug log. I'll verify with them.
