### ISSUE TITLE
Icons for annotation tools

### ISSUE THREAD

**Issue by michalrentka** [zotero/zotero-ios#871]
@yexingsha can you take a look at current icons of annotation tools that we have on iOS and desktop and probably unify them? If we don't want to unify them, I'll at least need new icons for text and underline annotations (#809). Currently I used some SF Symbols for those two.

![IMG_0595](https://github.com/zotero/zotero-ios/assets/1022956/298726ca-3088-4e36-8205-84cecc4909a0)

**Comment by yexingsha** [comment]
Let's unify them, here are the 28px icons in svg: [annotate-icons.zip](https://github.com/zotero/zotero-ios/files/14621818/annotate-icons.zip)

<img width="1112" alt="annotation" src="https://github.com/zotero/zotero-ios/assets/57771795/b0acae07-fa14-4fec-83ba-70b18871f490">

**Comment by pengxy0** [comment]
When will the underline feature be available in iOS? Always feel desktop and iPadOS side of the note method is not synchronized, let me feel very uncomfortable and inconvenient
！
