### ISSUE TITLE
Get people to mention iOS when posting crash logs

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#872]
https://forums.zotero.org/discussion/112693/ios-crash-log-sent

I'm constantly having to rename these threads to add "iOS" to the title. (This one was just "crash log sent".) Saying "iOS Crash Log Sent" would be awkward, but I'm not sure what else we can do. @fcheslack, unless we can open https://forums.zotero.org/post/discussion with a pre-populated discussion title?

**Comment by fcheslack** [comment]
Are people following a link for this? You can pre-populate the title by passing ?name=

**Comment by michalrentka** [comment]
@dstillman should we add title input there? And automatically add iOS?

**Comment by dstillman** [comment]
I think we can just hard-code it to "iOS Crash Report". People aren't going to fill in a meaningful title, and if someone is so inclined they can change it on the page.

**Comment by fcheslack** [comment]
You can pass ?body= for the message
