### ISSUE TITLE
Highlight annotations created in iOS may contain gaps in drawing

### ISSUE THREAD

**Issue by mvasilak** [zotero/zotero-ios#880]
https://forums.zotero.org/discussion/comment/458539
The issue appeared when we upgraded PSPDFKit from `13.3.1` to `13.3.2`.

Before:
<img width="178" alt="Selection-13 3 1" src="https://github.com/zotero/zotero-ios/assets/617841/a7666825-4c19-48a4-a4ca-ba799cad016e">
<img width="162" alt="Highlight-13 3 1" src="https://github.com/zotero/zotero-ios/assets/617841/144d8f11-1cbc-45ac-b318-c576f277220c">

After:
<img width="178" alt="Selection-13 3 2" src="https://github.com/zotero/zotero-ios/assets/617841/9fd815f5-f626-49ed-972b-cc17d4651f85">
<img width="166" alt="Highlight-13 3 2" src="https://github.com/zotero/zotero-ios/assets/617841/5c376cab-dea9-4f60-96ea-ef9cae189367">

I'll contact their support.

**Comment by mvasilak** [comment]
In the meantime, should we revert to the version where the issue does not appear and release a new version? WDYT @dstillman  @michalrentka ?

**Comment by dstillman** [comment]
Yes, it seems like we're going to get a lot of reports on this. We should revert if that won't cause other problems.

**Comment by mvasilak** [comment]
PSPDFKit confirmed it's a regression on their part. As we have reverted to the older working version, we'll update the dependency once this is fixed.

**Comment by michalrentka** [comment]
@mvasilak how is this looking? PSDPFKit 13.4.1 is out, does it still contain the issue?

**Comment by mvasilak** [comment]
Still waiting, their internal ticket for this is `J#CORE-510`, and they are also going to inform me when it is fixed.

**Comment by mvasilak** [comment]
Heard back from PSPDFKit support:
> I'm glad to tell you that the issue has been fixed and a patch will be available with our upcoming release.
