### ISSUE TITLE
Better error message in share extension when group doesn't allow file editing

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#881]
https://forums.zotero.org/discussion/112932/pdf-attachment-upload-fail-on-zotero-app-ipad-apple-due-to-an-unknown-error-occurred

**Comment by michalrentka** [comment]
@dstillman what should the error message say?

**Comment by michalrentka** [comment]
Also, should in this case the item be added and kept only locally? Because currently it's added and you get the warning "You can't write to group x anymore. What would you like to do?" "Keep changes" "Revert to original".

**Comment by dstillman** [comment]
> Also, should in this case the item be added and kept only locally? Because currently it's added and you get the warning "You can't write to group x anymore. What would you like to do?" "Keep changes" "Revert to original".

Sorry, missed this, but no, it shouldn't save to a library where it's known you don't have write access. But you should of course be able to switch to a different library.

The main sync process does need to account for the possibility of recent local changes after losing remote write access while offline, though:

https://github.com/zotero/zotero/blob/38287cec0705a1d7b652597086681d0564c456a0/chrome/locale/en-US/zotero/zotero.properties#L1034-L1037
