### ISSUE TITLE
Share extension causing updates to be skipped?

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#882]
This looks a lot like the share extension is advancing the library version without actually downloading objects.

```
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:08 -0500] "GET /users/xxxxxx/collections?format=versions&since=6887 HTTP/1.1" 200 2 "-" "ZShare/1.0.24 (org.zotero.ios.Zotero.ZShare; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:08 -0500] "GET /users/xxxxxx/groups?format=versions HTTP/1.1" 200 2 "-" "ZShare/1.0.24 (org.zotero.ios.Zotero.ZShare; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:16 -0500] "POST /users/xxxxxx/items/CIZHEBTQ/file HTTP/1.1" 200 12 "-" "ZShare/1.0.24 (org.zotero.ios.Zotero.ZShare; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:15 -0500] "POST /users/xxxxxx/items HTTP/1.1" 200 548 "-" "ZShare/1.0.24 (org.zotero.ios.Zotero.ZShare; build:222; iOS 17.3.0) Alamofire/5.8.0"

api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:21 -0500] "GET /users/xxxxxx/groups?format=versions HTTP/1.1" 200 2 "-" "Zotero/1.0.24 (org.zotero.ios.Zotero; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:21 -0500] "GET /users/xxxxxx/collections?format=versions&since=7195 HTTP/1.1" 200 2 "-" "Zotero/1.0.24 (org.zotero.ios.Zotero; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:21 -0500] "GET /users/xxxx/settings?since=6887 HTTP/1.1" 200 243 "-" "Zotero/1.0.24 (org.zotero.ios.Zotero; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:22 -0500] "GET /users/xxxx/items?format=versions&since=7197 HTTP/1.1" 304 - "-" "Zotero/1.0.24 (org.zotero.ios.Zotero; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:21 -0500] "GET /users/xxxx/searches?format=versions&since=6887 HTTP/1.1" 200 2 "-" "Zotero/1.0.24 (org.zotero.ios.Zotero; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:22 -0500] "GET /users/xxxx/items/trash?format=versions&since=6887 HTTP/1.1" 200 2 "-" "Zotero/1.0.24 (org.zotero.ios.Zotero; build:222; iOS 17.3.0) Alamofire/5.8.0"
api.zotero.org x.x.x.x - - [03/Mar/2024:11:59:22 -0500] "GET /users/xxxx/deleted?since=6887 HTTP/1.1" 200 317 "-" "Zotero/1.0.24 (org.zotero.ios.Zotero; build:222; iOS 17.3.0) Alamofire/5.8.0"
```

**Comment by dstillman** [comment]
Recent reports:

https://forums.zotero.org/discussion/112860/ios-syncing-issue
https://forums.zotero.org/discussion/112915/ios-not-syncing
https://forums.zotero.org/discussion/112952/some-items-fail-to-sync-from-computer-to-ios

**Comment by mvasilak** [comment]
Couldn't recreate such a scenario so far. During  sharing, sync happens always before advancing any versions. We can ask the users to describe how they use the share extension, to understand if there is an edge case we haven't covered,

**Comment by dstillman** [comment]
And that's the case even if the app is force-quit?

**Comment by dstillman** [comment]
Did you try with 1.0.24?

**Comment by dstillman** [comment]
Oh, wait, 1.0.24 is from November, not February. Maybe this is an old bug that we fixed, and these people were using outdated versions?

**Comment by mvasilak** [comment]
> And that's the case even if the app is force-quit?

It shouldn't matter, as the share extension itself will sync any changes in the local database.

**Comment by dstillman** [comment]
Well, it looks like the share extension just uploads new items without passing If-Unmodified-Since-Version (so presumably with `version: 0` for each object), so it doesn't need to download items at all and can let the app do that later.

But I figured it out. It's the file upload request. When there's a file, the version number gets advanced and the app misses remote updates.

1. Force-quit the app
2. On desktop, add an item
3. On iOS, save https://arxiv.org/abs/2307.03202
4. Open app and the item from the desktop won't be present

**Comment by dstillman** [comment]
Along with fixing this, we'd ideally trigger a "full sync" on upgrade — i.e., a sync that checks the versions of all objects in the online library and compares to the local versions, and then downloads updates. (It would also look for local changes that were missing remotely, but that wouldn't matter here.) I can't remember if we ever implemented code to do that on iOS.

**Comment by mvasilak** [comment]
I found out why my first tests didn't produce the error. I saved a science direct article, which always resulted to the ["ExtensionViewModel: upload authorized"](https://github.com/zotero/zotero-ios/blame/414f35538f488afff7f9db1453c33ffe9e13179a/ZShare/ViewModels/ExtensionViewModel.swift#L1144) case, that doesn't cause the issue.

When I saved the article you suggested @dstillman, it followed the alternate case ["ExtensionViewModel: file exists remotely"](https://github.com/zotero/zotero-ios/blame/414f35538f488afff7f9db1453c33ffe9e13179a/ZShare/ViewModels/ExtensionViewModel.swift#L1132), that indeed saves the items version, overlooking the unfetched changes. Removing that, resolves this issue.

**Comment by dstillman** [comment]
We previously [ran a full sync on startup](https://github.com/zotero/zotero-ios/commit/d2e98f154ad33e7d968b2ff304284216cf14616b) — seemingly to fix an [extremely similar bug](https://github.com/zotero/zotero-ios/commit/d5d42e0da715d62eca4dc650512268f586b22e2d) — but it looks like that was done as a one-off. If that's still what's in place, we should instead use a counter there that we can increment when this needs to be done, and then have it run for upgraders.
