### ISSUE TITLE
Expose "desktop-compatible" attachment storage through the Files app

### ISSUE THREAD

**Issue by tomodachi94** [zotero/zotero-ios#905]
I sync my `~/Zotero/storage` folder on desktop to various machines through Syncthing. I would like to be able to setup [Möbius Sync Pro](https://apps.apple.com/us/app/m%C3%B6bius-sync-pro/id1671184333)[^1] to sync my PDF collection directly into Zotero for iOS in the same way.

This would be possible if Zotero for iOS exposed its internal storage in the Files app, ideally in a way that is compatible with the desktop version of Zotero.

[^1]: This is possible through other apps as well, I just chose this one as an example.

**Comment by dstillman** [comment]
Please post all feature requests to the Zotero Forums.

https://github.com/zotero/zotero-ios/blob/master/CONTRIBUTING.md

But the iOS app doesn't store files the same way as the desktop and we have no plans to do this. If you'd like to access files in the iOS app, you can use Zotero Storage or WebDAV.
