### ISSUE TITLE
Add/restore "Copy to Clipboard" button when generating Debug ID

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#911]
https://forums.zotero.org/discussion/comment/461466/#Comment_461466

I can't remember what we had before, but I assume we had a way to copy the Debug ID to the clipboard? We still need that — if someone has an existing forum thread, "Submit to Zotero Forums" isn't helpful.

**Comment by michalrentka** [comment]
The ID is always copied to clipboard btw, but I'll re-add the "Copy to Clipboard" button so that it's not confusing.
