### ISSUE TITLE
Allow custom `Referer` in translation HTTP requests

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#962]
https://forums.zotero.org/discussion/115331/ieee-saver-doesn-t-work-any-more

Not confirmed, but seems likely that this is failing due to `Referer` not being passed with the `download-bibtex` request:

https://github.com/zotero/translators/blob/682cb285cd190a8df5fd684c5bd8e29003083454/IEEE%20Xplore.js#L153

**Comment by michalrentka** [comment]
@dstillman I fixed the missing `Referer` and item is correctly recognized as Journal Article. But on desktop I see that it even downloads the attachment and I don't get any attachments on iOS. Any ideas?

**Comment by dstillman** [comment]
You're likely just getting an open-access PDF on desktop. The PDF on that page isn't available.
