### ISSUE TITLE
Send deleted collections to the trash

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#982]
Setting `deleted: true` via the API

Particularly since we don't have a confirmation prompt when deleting a collection

(We could also support Undo for deleting collections, though that gets into the somewhat complicated question of when to clear undo history. And I'm not sure if enough people know about the stupid shake-to-undo gesture for it to be worth a lot of effort. But if we can do it easily, it'd be worth it.)

**Comment by michalrentka** [comment]
> (We could also support Undo for deleting collections, though that gets into the somewhat complicated question of when to clear undo history. And I'm not sure if enough people know about the stupid shake-to-undo gesture for it to be worth a lot of effort. But if we can do it easily, it'd be worth it.)

Rather than undo I'd recommend showing collections in trash so that they can be restored there. The shake-to-undo gesture is often unreliable and possibly most people wouldn't even try it (unless we show some popup info saying you can do that).

**Comment by dstillman** [comment]
Showing collections in the trash is what this ticket is for — we definitely need to do that.

I'm just saying that we could also support shake-to-undo if there's a straightforward way to 1) support it and 2) clear history after other library actions. It's a pretty bad gesture, but plenty of apps (at least built-in ones) do support it — including, e.g., for undoing moving messages to the trash in Mail, so it's not all that esoteric.

**Comment by michalrentka** [comment]
> Showing collections in the trash is what this ticket is for — we definitely need to do that.

Oh, from description I understood you only want to change the delete action from actually deleting to moving to trash. I'll implement the UI change as well. I see in desktop app we just show collections and items together. Do we maybe want to separate collections and items into different sections or just show them the same as on desktop?

> I'm just saying that we could also support shake-to-undo if there's a straightforward way to 1) support it and 2) clear history after other library actions. It's a pretty bad gesture, but plenty of apps (at least built-in ones) do support it — including, e.g., for undoing moving messages to the trash in Mail, so it's not all that esoteric.

I'll check the gesture, it should be easy to detect, but we'll have to handle the history ourselves.

**Comment by dstillman** [comment]
Ah, sorry, I meant the UI part too.

> I see in desktop app we just show collections and items together. Do we maybe want to separate collections and items into different sections or just show them the same as on desktop?

A single list is fine. I would guess that that's actually more complicated than two separate lists? On the desktop we had to do various things to have collections pretend to be items to fulfill expectations of the items list. But I do think that's what people will expect and that separate sections would be a little weird for a trash view.

**Comment by michalrentka** [comment]
Yes, single list will complicate things a bit, but we can make it work.
