### ISSUE TITLE
Avoid overlapping highlighting with tighter line spacing

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#984]
https://forums.zotero.org/discussion/comment/468295/#Comment_468295

I assume this is an issue for PSPDFKit, but the desktop one seems arguably more correct.

**Comment by mvasilak** [comment]
Indeed these are the selection/highlight rects provided by PSPDFKit, we can transform them if we wish, according to some simple overlap detection logic. We can ask PSPDFKit support first, just in case they have a better suggestion. @mrtcode you mention some normalizing logic in the desktop client, can you please point to the relevant code?

**Comment by mrtcode** [comment]
Sure.

https://github.com/zotero/pdf.js/blob/449f8ddf0d668323dcb49a63011d7037ba5432d7/src/core/evaluator.js#L2982-L3005
